// frontend-react/src/pages/CoursesPage.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getCourses } from '../api/courseApi';
import { useAuth } from '../context/AuthContext';
import { List, Card, Typography, Spin } from 'antd';

const { Title } = Typography;

const CoursesPage = () => {
    const { user } = useAuth();
    const navigate = useNavigate();
    const [courses, setCourses] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchCourses = async () => {
            setLoading(true);
            try {
                const params = {
                    userId: user.id,
                    roles: user.roles,
                    size: 100,
                };
                const res = await getCourses(params);
                setCourses(res.data.content);
            } catch (error) {
                console.error(error);
            } finally {
                setLoading(false);
            }
        };
        fetchCourses();
    }, [user]);

    if (loading) return <Spin tip="Загрузка..." />;

    const grouped = courses.reduce((acc, course) => {
        const catName = course.category?.name || 'Без категории';
        if (!acc[catName]) acc[catName] = [];
        acc[catName].push(course);
        return acc;
    }, {});

    return (
        <div>
            <Title level={2}>Доступные курсы</Title>
            {Object.keys(grouped).length === 0 && <p>Нет доступных курсов</p>}
            {Object.entries(grouped).map(([category, items]) => (
                <div key={category} style={{ marginBottom: 24 }}>
                    <Title level={4}>{category}</Title>
                    <List
                        grid={{ gutter: 16, column: 3 }}
                        dataSource={items}
                        renderItem={course => (
                            <List.Item>
                                <Card
                                    hoverable
                                    onClick={() => navigate(`/courses/${course.id}`)}
                                    title={course.title}
                                >
                                    {course.description}
                                    <br />
                                    <strong>Преподаватель:</strong> {course.teacher?.fullName || 'Не указан'}
                                </Card>
                            </List.Item>
                        )}
                    />
                </div>
            ))}
        </div>
    );
};

export default CoursesPage;

// frontend-angular/src/app/pages/courses-page/courses-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CourseService } from '../../api/course.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { catchError, finalize } from 'rxjs/operators';
import { of } from 'rxjs';

@Component({
    selector: 'app-courses-page',
    templateUrl: './courses-page.component.html',
    styleUrls: ['./courses-page.component.scss']
})
export class CoursesPageComponent implements OnInit {
    courses: any[] = [];
    loading = true;

    constructor(
        private courseService: CourseService,
        private auth: AuthService,
        private router: Router,
        private message: NzMessageService
    ) {}

    ngOnInit(): void {
        this.loadCourses();
    }

    loadCourses(): void {
        this.loading = true;
        const user = this.auth.getUser();
        if (!user) {
            this.message.error('Пользователь не авторизован');
            this.loading = false;
            return;
        }
        const params = {
            userId: user.id,
            roles: this.auth.getRolesString(),
            size: 100
        };
        this.courseService.getCourses(params)
            .pipe(
                catchError(() => {
                    this.message.error('Не удалось загрузить курсы');
                    this.courses = [];
                    this.loading = false;
                    return of({ content: [] });
                }),
                finalize(() => {
                    this.loading = false;
                })
            )
            .subscribe({
                next: (res) => {
                    this.courses = res.content || [];
                }
            });
    }

    get groupedCourses(): { [key: string]: any[] } {
        if (!Array.isArray(this.courses)) return {};
        return this.courses.reduce((acc, course) => {
            const catName = course.category?.name || 'Без категории';
            if (!acc[catName]) acc[catName] = [];
            acc[catName].push(course);
            return acc;
        }, {} as { [key: string]: any[] });
    }

    navigateToCourse(id: number): void {
        this.router.navigate(['/courses', id]);
    }

    trackByCategory(index: number, item: any): string {
        return item.key;
    }

    trackByCourse(index: number, course: any): number {
        return course.id;
    }
}
<div class="container">
    <h2>Доступные курсы</h2>
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="!loading && courses.length === 0">
            <p>Нет доступных курсов</p>
        </div>
        <nz-collapse *ngIf="!loading && courses.length > 0">
            <nz-collapse-panel
                    *ngFor="let category of groupedCourses | keyvalue; trackBy: trackByCategory"
                    [nzHeader]="category.key"
                    [nzActive]="true">
                <nz-list [nzGrid]="{ gutter: 16, column: 3 }">
                    <nz-list-item *ngFor="let course of category.value; trackBy: trackByCourse">
                        <nz-card [nzTitle]="course.title" (click)="navigateToCourse(course.id)" nzHoverable>
                            <p>{{ course.description }}</p>
                            <p><strong>Преподаватель:</strong> {{ course.teacher?.fullName || 'Не указан' }}</p>
                        </nz-card>
                    </nz-list-item>
                </nz-list>
            </nz-collapse-panel>
        </nz-collapse>
    </nz-spin>
</div>
