// frontend-react/src/components/TestAttemptList.js
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Modal, Form, InputNumber, Select, Input, message, Spin } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { getTestAttempts, createTestAttempt, updateTestAttempt, deleteTestAttempt } from '../api/testAttemptApi';
import { getAllTests } from '../api/testApi';
import { getAllUsers } from '../api/userApi';
import { formatDateTime } from '../utils/dateUtils';
import { useAuth } from '../context/AuthContext';

const { Column } = Table;
const { Option } = Select;

const translateStatus = (status) => {
    const map = {
        'IN_PROGRESS': 'В процессе',
        'COMPLETED': 'Завершено',
        'FAILED': 'Провалено'
    };
    return map[status] || status;
};

const TestAttemptList = () => {
    const { user } = useAuth();
    const isAdmin = user.roles?.includes('ADMIN') || false;

    const [attempts, setAttempts] = useState([]);
    const [tests, setTests] = useState([]);
    const [users, setUsers] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingAttempt, setEditingAttempt] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        testTitle: '',
        userUsername: '',
        currentUserId: user.id,
        roles: user.roles ? user.roles.join(',') : '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        const fetchSelects = async () => {
            try {
                const [testsRes, usersRes] = await Promise.all([
                    getAllTests(),
                    getAllUsers()
                ]);
                setTests(testsRes.data.content || testsRes.data);
                setUsers(usersRes.data.content || usersRes.data);
            } catch {
                message.error('Не удалось загрузить справочники');
            }
        };
        fetchSelects();
    }, []);

    useEffect(() => {
        fetchAttempts();
    }, [queryParams]);

    const fetchAttempts = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.testTitle) delete params.testTitle;
            if (!params.userUsername) delete params.userUsername;
            const res = await getTestAttempts(params);
            setAttempts(res.data.content);
            setPaginationInfo({
                current: res.data.number + 1,
                pageSize: res.data.size,
                total: res.data.totalElements,
            });
        } catch {
            message.error('Не удалось загрузить попытки');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (field) => (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                [field]: value,
                page: 0,
            }));
        }, 300);
    };

    const handleReset = () => {
        setQueryParams(prev => ({
            ...prev,
            page: 0,
            testTitle: '',
            userUsername: '',
        }));
    };

    const showModal = (attempt = null) => {
        setEditingAttempt(attempt);
        form.resetFields();
        if (attempt) {
            form.setFieldsValue({
                attemptNumber: attempt.attemptNumber,
                startTime: attempt.startTime,
                endTime: attempt.endTime,
                score: attempt.score,
                status: attempt.status,
                testId: attempt.test?.id,
                userId: attempt.user?.id,
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingAttempt) {
                await updateTestAttempt(editingAttempt.id, values);
                message.success('Попытка обновлена');
            } else {
                await createTestAttempt(values);
                message.success('Попытка создана');
            }
            setModalVisible(false);
            fetchAttempts();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить попытку?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteTestAttempt(id);
                    message.success('Попытка удалена');
                    fetchAttempts();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space wrap>
                        <Input
                            placeholder="Поиск по названию теста"
                            allowClear
                            value={queryParams.testTitle}
                            onChange={handleSearchChange('testTitle')}
                            style={{ width: 200 }}
                        />
                        <Input
                            placeholder="Поиск по логину пользователя"
                            allowClear
                            value={queryParams.userUsername}
                            onChange={handleSearchChange('userUsername')}
                            style={{ width: 200 }}
                        />
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    {isAdmin && (
                        <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                            Добавить попытку
                        </Button>
                    )}
                </div>

                <Table
                    dataSource={attempts}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    {isAdmin && <Column title="ID" dataIndex="id" />}
                    <Column
                        title="Тест"
                        render={(_, a) => a.test ? <Link to={`/tests/${a.test.id}`}>{a.test.title}</Link> : '—'}
                    />
                    <Column
                        title="Пользователь"
                        render={(_, a) => a.user?.username || '—'}
                    />
                    <Column title="Попытка №" dataIndex="attemptNumber" />
                    <Column title="Начало" render={(_, a) => formatDateTime(a.startTime)} />
                    <Column title="Конец" render={(_, a) => formatDateTime(a.endTime)} />
                    <Column title="Балл" dataIndex="score" />
                    <Column title="Статус" render={(_, a) => translateStatus(a.status)} />
                    {isAdmin && (
                        <Column
                            title="Действия"
                            render={(_, attempt) => (
                                <Space>
                                    <Button icon={<EditOutlined />} onClick={() => showModal(attempt)} />
                                    <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(attempt.id)} />
                                </Space>
                            )}
                        />
                    )}
                </Table>

                <Modal
                    title={editingAttempt ? 'Редактировать попытку' : 'Новая попытка'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                    width={600}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="testId" label="Тест" rules={[{ required: true }]}>
                            <Select placeholder="Выберите тест">
                                {tests.map(test => (
                                    <Option key={test.id} value={test.id}>{test.title}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                        <Form.Item name="userId" label="Пользователь" rules={[{ required: true }]}>
                            <Select placeholder="Выберите пользователя">
                                {users.map(user => (
                                    <Option key={user.id} value={user.id}>{user.username}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                        <Form.Item
                            name="attemptNumber"
                            label="Номер попытки"
                            rules={[{ required: true, type: 'number', message: 'Введите число' }]}
                        >
                            <InputNumber style={{ width: '100%' }} min={1} step={1} />
                        </Form.Item>
                        <Form.Item name="startTime" label="Время начала">
                            <Input placeholder="YYYY-MM-DDTHH:mm:ss" />
                        </Form.Item>
                        <Form.Item name="endTime" label="Время окончания">
                            <Input placeholder="YYYY-MM-DDTHH:mm:ss" />
                        </Form.Item>
                        <Form.Item name="score" label="Балл">
                            <InputNumber style={{ width: '100%' }} min={0} step={1} />
                        </Form.Item>
                        <Form.Item name="status" label="Статус">
                            <Select placeholder="Выберите статус">
                                <Option value="IN_PROGRESS">В процессе</Option>
                                <Option value="COMPLETED">Завершено</Option>
                                <Option value="FAILED">Провалено</Option>
                            </Select>
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default TestAttemptList;

// frontend-angular/src/app/components/test-attempt-list/test-attempt-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { TestAttemptService } from '../../api/test-attempt.service';
import { TestService } from '../../api/test.service';
import { UserService } from '../../api/user.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';
import { formatDateTime } from '../../utils/date-utils';

@Component({
    selector: 'app-test-attempt-list',
    templateUrl: './test-attempt-list.component.html',
    styleUrls: ['./test-attempt-list.component.scss']
})
export class TestAttemptListComponent implements OnInit {
    attempts: any[] = [];
    tests: any[] = [];
    users: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchTestTitle = '';
    searchUserUsername = '';
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private testAttemptService: TestAttemptService,
        private testService: TestService,
        private userService: UserService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService,
        private cdr: ChangeDetectorRef
    ) {
        this.form = this.fb.group({
            testId: [null, Validators.required],
            userId: [null, Validators.required],
            attemptNumber: [null, [Validators.required, Validators.min(1)]],
            startTime: [null],
            endTime: [null],
            score: [null],
            status: [null]
        });
    }

    ngOnInit(): void {
        this.loadSelectData();
        this.loadAttempts();
    }

    formatDate(date: string): string {
        return formatDateTime(date);
    }

    translateStatus(status: string): string {
        const map: { [key: string]: string } = {
            'IN_PROGRESS': 'В процессе',
            'COMPLETED': 'Завершено'
        };
        return map[status] || status;
    }

    formatDateForInput(date: string | null): string | null {
        if (!date) return null;
        const d = new Date(date);
        const year = d.getFullYear();
        const month = String(d.getMonth() + 1).padStart(2, '0');
        const day = String(d.getDate()).padStart(2, '0');
        const hours = String(d.getHours()).padStart(2, '0');
        const minutes = String(d.getMinutes()).padStart(2, '0');
        return `${year}-${month}-${day}T${hours}:${minutes}`;
    }

    loadSelectData(): void {
        this.testService.getAllTests().subscribe({
            next: (res) => {
                this.tests = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => {
                this.message.error('Не удалось загрузить тесты');
            }
        });
        this.userService.getAllUsers().subscribe({
            next: (res) => {
                this.users = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => {
                this.message.error('Не удалось загрузить пользователей');
            }
        });
    }

    loadAttempts(): void {
        this.loading = true;
        const params: any = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            currentUserId: this.auth.getUser()?.id,
            roles: this.auth.getRolesString()
        };
        if (this.searchTestTitle) params.testTitle = this.searchTestTitle;
        if (this.searchUserUsername) params.userUsername = this.searchUserUsername;
        this.testAttemptService.getTestAttempts(params).subscribe({
            next: (res) => {
                this.attempts = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить попытки');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadAttempts();
    }

    resetFilters(): void {
        this.searchTestTitle = '';
        this.searchUserUsername = '';
        this.pageIndex = 1;
        this.loadAttempts();
    }

    canManage(): boolean {
        return this.auth.isAdmin();
    }

    showModal(data?: any): void {
        if (this.tests.length === 0 || this.users.length === 0) {
            this.loadSelectData();
        }
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                testId: data.test?.id || null,
                userId: data.user?.id || null,
                attemptNumber: data.attemptNumber,
                startTime: this.formatDateForInput(data.startTime),
                endTime: this.formatDateForInput(data.endTime),
                score: data.score,
                status: data.status
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.testAttemptService.updateTestAttempt(this.editId!, values)
            : this.testAttemptService.createTestAttempt(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Попытка обновлена' : 'Попытка создана');
                this.isVisible = false;
                this.loadAttempts();
            },
            error: (err) => {
                this.message.error(err.error?.message || 'Ошибка сохранения');
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteAttempt(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить попытку?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOkType: 'primary',
            nzOnOk: () => {
                this.testAttemptService.deleteTestAttempt(id).subscribe({
                    next: () => {
                        this.message.success('Попытка удалена');
                        this.loadAttempts();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    searchTimeout: any;

    onSearchChange1(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchTestTitle = value;
            this.pageIndex = 1;
            this.loadAttempts();
        }, 300);
    }

    onSearchChange2(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchUserUsername = value;
            this.pageIndex = 1;
            this.loadAttempts();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию теста" [(ngModel)]="searchTestTitle" (ngModelChange)="onSearchChange1($event)" style="width:250px;" />
        <input nz-input placeholder="Поиск по логину пользователя" [(ngModel)]="searchUserUsername" (ngModelChange)="onSearchChange2($event)" style="width:250px;" />
        <button nz-button (click)="resetFilters()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="canManage()" (click)="showModal()" class="add-btn">Добавить попытку</button>
    </div>

    <nz-table
            [nzData]="attempts"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="canManage()">ID</th>
            <th>Тест</th>
            <th>Пользователь</th>
            <th>Попытка №</th>
            <th>Начало</th>
            <th>Конец</th>
            <th>Балл</th>
            <th>Статус</th>
            <th *ngIf="canManage()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let attempt of attempts">
            <td *ngIf="canManage()">{{ attempt.id }}</td>
            <td><a *ngIf="attempt.test" [routerLink]="['/tests', attempt.test.id]">{{ attempt.test.title }}</a></td>
            <td>{{ attempt.user?.username || '—' }}</td>
            <td>{{ attempt.attemptNumber }}</td>
            <td>{{ formatDate(attempt.startTime) }}</td>
            <td>{{ formatDate(attempt.endTime) }}</td>
            <td>{{ attempt.score }}</td>
            <td>{{ translateStatus(attempt.status) }}</td>
            <td *ngIf="canManage()">
                <button nz-button nzType="link" (click)="showModal(attempt)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger (click)="deleteAttempt(attempt.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать попытку' : 'Новая попытка'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
            [nzWidth]="600"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Тест</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <nz-select *ngIf="tests.length > 0" formControlName="testId" nzPlaceHolder="Выберите тест">
                            <nz-option *ngFor="let test of tests" [nzValue]="test.id" [nzLabel]="test.title"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="tests.length === 0" nzPlaceHolder="Загрузка тестов..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Пользователь</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <nz-select *ngIf="users.length > 0" formControlName="userId" nzPlaceHolder="Выберите пользователя">
                            <nz-option *ngFor="let user of users" [nzValue]="user.id" [nzLabel]="user.username"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="users.length === 0" nzPlaceHolder="Загрузка пользователей..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Номер попытки</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Введите число больше 0'">
                        <input nz-input type="number" formControlName="attemptNumber" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Время начала</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="datetime-local" formControlName="startTime" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Время окончания</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="datetime-local" formControlName="endTime" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Балл</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="number" formControlName="score" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Статус</nz-form-label>
                    <nz-form-control>
                        <nz-select formControlName="status" nzPlaceHolder="Выберите статус">
                            <nz-option nzValue="IN_PROGRESS" nzLabel="В процессе"></nz-option>
                            <nz-option nzValue="COMPLETED" nzLabel="Завершено"></nz-option>
                        </nz-select>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>
