// frontend-angular/src/app/components/course-list/course-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CourseService } from '../../api/course.service';
import { CategoryService } from '../../api/category.service';
import { UserService } from '../../api/user.service';
import { RoleService } from '../../api/role.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
    selector: 'app-course-list',
    templateUrl: './course-list.component.html',
    styleUrls: ['./course-list.component.scss']
})
export class CourseListComponent implements OnInit {
    courses: any[] = [];
    categories: any[] = [];
    teachers: any[] = [];
    roles: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchTitle = '';
    filterCategoryId: number | null = null;
    filterTeacherId: number | null = null;
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private courseService: CourseService,
        private categoryService: CategoryService,
        private userService: UserService,
        private roleService: RoleService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService,
        private cdr: ChangeDetectorRef
    ) {
        this.form = this.fb.group({
            title: ['', Validators.required],
            description: [''],
            categoryId: [null],
            teacherId: [null, Validators.required],
            roleIds: [[]]
        });
    }

    ngOnInit(): void {
        this.loadSelectData();
        this.loadCourses();
    }

    loadSelectData(): void {
        this.categoryService.getAllCategories().subscribe({
            next: (res) => {
                this.categories = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить категории')
        });
        this.userService.getAllUsers().subscribe({
            next: (res) => {
                this.teachers = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить преподавателей')
        });
        this.roleService.getAllRoles().subscribe({
            next: (res) => {
                this.roles = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить роли')
        });
    }

    loadCourses(): void {
        this.loading = true;
        const params: any = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            userId: this.auth.getUser()?.id,
            roles: this.auth.getRolesString()
        };
        if (this.searchTitle) params.title = this.searchTitle;
        if (this.filterCategoryId) params.categoryId = this.filterCategoryId;
        if (this.filterTeacherId) params.teacherId = this.filterTeacherId;
        this.courseService.getCourses(params).subscribe({
            next: (res) => {
                this.courses = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить курсы');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadCourses();
    }

    resetFilters(): void {
        this.searchTitle = '';
        this.filterCategoryId = null;
        this.filterTeacherId = null;
        this.pageIndex = 1;
        this.loadCourses();
    }

    canEdit(course: any): boolean {
        return this.auth.isAdmin() || (this.auth.isTeacher() && course.teacher?.id === this.auth.getUser()?.id);
    }

    canCreate(): boolean {
        return this.auth.isAdmin() || this.auth.isTeacher();
    }

    showModal(data?: any): void {
        if (this.categories.length === 0 || this.teachers.length === 0 || this.roles.length === 0) {
            this.loadSelectData();
        }
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                title: data.title,
                description: data.description,
                categoryId: data.category?.id || null,
                teacherId: data.teacher?.id || null,
                roleIds: data.roles?.map((r: any) => r.id) || []
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.courseService.updateCourse(this.editId!, values)
            : this.courseService.createCourse(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Курс обновлён' : 'Курс создан');
                this.isVisible = false;
                this.loadCourses();
            },
            error: (err) => {
                this.message.error(err.error?.message || 'Ошибка сохранения');
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteCourse(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить курс?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOnOk: () => {
                this.courseService.deleteCourse(id).subscribe({
                    next: () => {
                        this.message.success('Курс удалён');
                        this.loadCourses();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchTitle = value;
            this.pageIndex = 1;
            this.loadCourses();
        }, 300);
    }

    onFilterChange(): void {
        this.pageIndex = 1;
        this.loadCourses();
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию" [(ngModel)]="searchTitle" (ngModelChange)="onSearchChange($event)" style="width:200px;" />
        <nz-select *ngIf="categories.length > 0" [(ngModel)]="filterCategoryId" nzPlaceHolder="Категория" nzAllowClear (ngModelChange)="onFilterChange()" style="width:150px;">
            <nz-option *ngFor="let cat of categories" [nzValue]="cat.id" [nzLabel]="cat.name"></nz-option>
        </nz-select>
        <nz-select *ngIf="categories.length === 0" nzPlaceHolder="Загрузка категорий..." disabled style="width:150px;"></nz-select>
        <nz-select *ngIf="teachers.length > 0" [(ngModel)]="filterTeacherId" nzPlaceHolder="Преподаватель" nzAllowClear (ngModelChange)="onFilterChange()" style="width:150px;">
            <nz-option *ngFor="let user of teachers" [nzValue]="user.id" [nzLabel]="user.fullName || user.username"></nz-option>
        </nz-select>
        <nz-select *ngIf="teachers.length === 0" nzPlaceHolder="Загрузка преподавателей..." disabled style="width:150px;"></nz-select>
        <button nz-button (click)="resetFilters()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="canCreate()" (click)="showModal()" class="add-btn">Добавить курс</button>
    </div>

    <nz-table
            [nzData]="courses"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="auth.isAdmin()">ID</th>
            <th>Название</th>
            <th>Категория</th>
            <th>Преподаватель</th>
            <th>Роли (доступ)</th>
            <th *ngIf="canCreate()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let course of courses">
            <td *ngIf="auth.isAdmin()">{{ course.id }}</td>
            <td><a [routerLink]="['/courses', course.id]">{{ course.title }}</a></td>
            <td><a *ngIf="course.category" [routerLink]="['/categories', course.category.id]">{{ course.category.name }}</a></td>
            <td>{{ course.teacher?.fullName || '—' }}</td>
            <td>
                <nz-tag *ngFor="let role of course.roles" nzColor="blue" [routerLink]="['/roles', role.id]">{{ role.name }}</nz-tag>
            </td>
            <td *ngIf="canCreate()">
                <button nz-button nzType="link" *ngIf="canEdit(course)" (click)="showModal(course)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger *ngIf="canEdit(course)" (click)="deleteCourse(course.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать курс' : 'Новый курс'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
            [nzWidth]="700"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Название</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="title" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Описание</nz-form-label>
                    <nz-form-control>
                        <textarea nz-input formControlName="description"></textarea>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Категория</nz-form-label>
                    <nz-form-control>
                        <nz-select *ngIf="categories.length > 0" formControlName="categoryId" nzAllowClear nzPlaceHolder="Выберите категорию">
                            <nz-option *ngFor="let cat of categories" [nzValue]="cat.id" [nzLabel]="cat.name"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="categories.length === 0" nzPlaceHolder="Загрузка категорий..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Преподаватель</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <nz-select *ngIf="teachers.length > 0" formControlName="teacherId" nzPlaceHolder="Выберите преподавателя">
                            <nz-option *ngFor="let user of teachers" [nzValue]="user.id" [nzLabel]="user.fullName || user.username"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="teachers.length === 0" nzPlaceHolder="Загрузка преподавателей..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Роли (доступ)</nz-form-label>
                    <nz-form-control>
                        <nz-select *ngIf="roles.length > 0" formControlName="roleIds" nzMode="multiple" nzPlaceHolder="Выберите роли">
                            <nz-option *ngFor="let role of roles" [nzValue]="role.id" [nzLabel]="role.name"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="roles.length === 0" nzPlaceHolder="Загрузка ролей..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>

// frontend-react/src/components/CourseList.js
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Modal, Form, Input, Select, Tag, message, Spin } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { getCourses, createCourse, updateCourse, deleteCourse } from '../api/courseApi';
import { getAllCategories } from '../api/categoryApi';
import { getAllUsers } from '../api/userApi';
import { getAllRoles } from '../api/roleApi';
import { useAuth } from '../context/AuthContext';

const { Column } = Table;
const { Option } = Select;

const CourseList = () => {
    const { user } = useAuth();
    const isAdmin = user.roles?.includes('ADMIN') || false;
    const isTeacher = user.roles?.includes('TEACHER') || false;

    const [courses, setCourses] = useState([]);
    const [categories, setCategories] = useState([]);
    const [teachers, setTeachers] = useState([]);
    const [roles, setRoles] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingCourse, setEditingCourse] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        title: '',
        categoryId: undefined,
        teacherId: undefined,
        userId: user.id,
        roles: user.roles ? user.roles.join(',') : '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        const fetchSelects = async () => {
            try {
                const [catRes, teachRes, roleRes] = await Promise.all([
                    getAllCategories(),
                    getAllUsers(),
                    getAllRoles(),
                ]);
                setCategories(catRes.data.content || catRes.data);
                setTeachers(teachRes.data.content || teachRes.data);
                setRoles(roleRes.data.content || roleRes.data);
            } catch {
                message.error('Не удалось загрузить справочники');
            }
        };
        fetchSelects();
    }, []);

    useEffect(() => {
        fetchCourses();
    }, [queryParams]);

    const fetchCourses = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.title) delete params.title;
            if (params.categoryId === undefined) delete params.categoryId;
            if (params.teacherId === undefined) delete params.teacherId;
            // userId и roles всегда есть, их не удаляем
            const res = await getCourses(params);
            setCourses(res.data.content);
            setPaginationInfo({
                current: res.data.number + 1,
                pageSize: res.data.size,
                total: res.data.totalElements,
            });
        } catch {
            message.error('Не удалось загрузить курсы');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                title: value,
                page: 0,
            }));
        }, 300);
    };

    const handleFilterChange = (field, value) => {
        setQueryParams(prev => ({
            ...prev,
            [field]: value,
            page: 0,
        }));
    };

    const handleReset = () => {
        setQueryParams(prev => ({
            ...prev,
            page: 0,
            title: '',
            categoryId: undefined,
            teacherId: undefined,
        }));
    };

    const showModal = (course = null) => {
        setEditingCourse(course);
        form.resetFields();
        if (course) {
            form.setFieldsValue({
                title: course.title,
                description: course.description,
                categoryId: course.category?.id,
                teacherId: course.teacher?.id,
                roleIds: course.roles?.map(r => r.id) || [],
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingCourse) {
                await updateCourse(editingCourse.id, values);
                message.success('Курс обновлён');
            } else {
                await createCourse(values);
                message.success('Курс создан');
            }
            setModalVisible(false);
            fetchCourses();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить курс?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteCourse(id);
                    message.success('Курс удалён');
                    fetchCourses();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    const canEdit = (course) => {
        return isAdmin || (isTeacher && course.teacher?.id === user.id);
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space wrap>
                        <Input
                            placeholder="Поиск по названию"
                            allowClear
                            value={queryParams.title}
                            onChange={handleSearchChange}
                            style={{ width: 200 }}
                        />
                        <Select
                            placeholder="Категория"
                            allowClear
                            style={{ width: 150 }}
                            value={queryParams.categoryId}
                            onChange={(value) => handleFilterChange('categoryId', value)}
                        >
                            {categories.map(cat => (
                                <Option key={cat.id} value={cat.id}>{cat.name}</Option>
                            ))}
                        </Select>
                        <Select
                            placeholder="Преподаватель"
                            allowClear
                            style={{ width: 150 }}
                            value={queryParams.teacherId}
                            onChange={(value) => handleFilterChange('teacherId', value)}
                        >
                            {teachers.map(user => (
                                <Option key={user.id} value={user.id}>
                                    {user.fullName || user.username}
                                </Option>
                            ))}
                        </Select>
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    {(isAdmin || isTeacher) && (
                        <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                            Добавить курс
                        </Button>
                    )}
                </div>

                <Table
                    dataSource={courses}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    {isAdmin && <Column title="ID" dataIndex="id" />}
                    <Column
                        title="Название"
                        render={(_, c) => <Link to={`/courses/${c.id}`}>{c.title}</Link>}
                    />
                    <Column
                        title="Категория"
                        render={(_, c) => c.category ? <Link to={`/categories/${c.category.id}`}>{c.category.name}</Link> : '—'}
                    />
                    <Column title="Преподаватель" render={(_, c) => c.teacher?.fullName || '—'} />
                    <Column
                        title="Роли (доступ)"
                        render={(_, c) => (
                            <Space wrap>
                                {c.roles?.map(role => (
                                    <Link key={role.id} to={`/roles/${role.id}`}>
                                        <Tag color="blue">{role.name}</Tag>
                                    </Link>
                                )) || '—'}
                            </Space>
                        )}
                    />
                    {(isAdmin || isTeacher) && (
                        <Column
                            title="Действия"
                            render={(_, course) => {
                                if (!canEdit(course)) return null;
                                return (
                                    <Space>
                                        <Button icon={<EditOutlined />} onClick={() => showModal(course)} />
                                        <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(course.id)} />
                                    </Space>
                                );
                            }}
                        />
                    )}
                </Table>

                <Modal
                    title={editingCourse ? 'Редактировать курс' : 'Новый курс'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                    width={700}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="title" label="Название" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="description" label="Описание">
                            <Input.TextArea />
                        </Form.Item>
                        <Form.Item name="categoryId" label="Категория">
                            <Select placeholder="Выберите категорию" allowClear>
                                {categories.map(cat => (
                                    <Option key={cat.id} value={cat.id}>{cat.name}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                        <Form.Item name="teacherId" label="Преподаватель" rules={[{ required: true }]}>
                            <Select placeholder="Выберите преподавателя">
                                {teachers.map(user => (
                                    <Option key={user.id} value={user.id}>
                                        {user.fullName || user.username}
                                    </Option>
                                ))}
                            </Select>
                        </Form.Item>
                        <Form.Item name="roleIds" label="Роли (доступ)">
                            <Select mode="multiple" placeholder="Выберите роли">
                                {roles.map(role => (
                                    <Option key={role.id} value={role.id}>{role.name}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default CourseList;
