// frontend-angular/src/app/components/lecture-list/lecture-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LectureService } from '../../api/lecture.service';
import { CourseService } from '../../api/course.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
    selector: 'app-lecture-list',
    templateUrl: './lecture-list.component.html',
    styleUrls: ['./lecture-list.component.scss']
})
export class LectureListComponent implements OnInit {
    lectures: any[] = [];
    courses: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchTitle = '';
    filterCourseId: number | null = null;
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private lectureService: LectureService,
        private courseService: CourseService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService,
        private cdr: ChangeDetectorRef
    ) {
        this.form = this.fb.group({
            title: ['', Validators.required],
            content: [''],
            orderNumber: [null],
            courseId: [null, Validators.required]
        });
    }

    ngOnInit(): void {
        this.loadCourses();
        this.loadLectures();
    }

    loadCourses(): void {
        this.courseService.getAllCourses().subscribe({
            next: (res) => {
                this.courses = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить курсы')
        });
    }

    loadLectures(): void {
        this.loading = true;
        const params: any = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            userId: this.auth.getUser()?.id,
            roles: this.auth.getRolesString()
        };
        if (this.searchTitle) params.title = this.searchTitle;
        if (this.filterCourseId) params.courseId = this.filterCourseId;
        this.lectureService.getLectures(params).subscribe({
            next: (res) => {
                this.lectures = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить лекции');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadLectures();
    }

    resetFilters(): void {
        this.searchTitle = '';
        this.filterCourseId = null;
        this.pageIndex = 1;
        this.loadLectures();
    }

    canEdit(lecture: any): boolean {
        return this.auth.isAdmin() || (this.auth.isTeacher() && lecture.course?.teacher?.id === this.auth.getUser()?.id);
    }

    canCreate(): boolean {
        return this.auth.isAdmin() || this.auth.isTeacher();
    }

    showModal(data?: any): void {
        if (this.courses.length === 0) {
            this.loadCourses();
        }
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                title: data.title,
                content: data.content,
                orderNumber: data.orderNumber,
                courseId: data.course?.id || null
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.lectureService.updateLecture(this.editId!, values)
            : this.lectureService.createLecture(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Лекция обновлена' : 'Лекция создана');
                this.isVisible = false;
                this.loadLectures();
            },
            error: (err) => {
                this.message.error(err.error?.message || 'Ошибка сохранения');
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteLecture(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить лекцию?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOkType: 'primary',
            nzOnOk: () => {
                this.lectureService.deleteLecture(id).subscribe({
                    next: () => {
                        this.message.success('Лекция удалена');
                        this.loadLectures();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchTitle = value;
            this.pageIndex = 1;
            this.loadLectures();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию" [(ngModel)]="searchTitle" (ngModelChange)="onSearchChange($event)" style="width:250px;" />
        <nz-select *ngIf="courses.length > 0" [(ngModel)]="filterCourseId" nzPlaceHolder="Курс" nzAllowClear (ngModelChange)="loadLectures()" style="width:180px;">
            <nz-option *ngFor="let course of courses" [nzValue]="course.id" [nzLabel]="course.title"></nz-option>
        </nz-select>
        <nz-select *ngIf="courses.length === 0" nzPlaceHolder="Загрузка курсов..." disabled style="width:180px;"></nz-select>
        <button nz-button (click)="resetFilters()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="canCreate()" class="add-btn" (click)="showModal()">Добавить лекцию</button>
    </div>

    <nz-table
            [nzData]="lectures"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="auth.isAdmin()">ID</th>
            <th>Название</th>
            <th>Курс</th>
            <th>Порядок</th>
            <th *ngIf="canCreate()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let lecture of lectures">
            <td *ngIf="auth.isAdmin()">{{ lecture.id }}</td>
            <td><a [routerLink]="['/lectures', lecture.id]">{{ lecture.title }}</a></td>
            <td><a *ngIf="lecture.course" [routerLink]="['/courses', lecture.course.id]">{{ lecture.course.title }}</a></td>
            <td>{{ lecture.orderNumber }}</td>
            <td *ngIf="canCreate()">
                <button nz-button nzType="link" *ngIf="canEdit(lecture)" (click)="showModal(lecture)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger *ngIf="canEdit(lecture)" (click)="deleteLecture(lecture.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать лекцию' : 'Новая лекция'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
            [nzWidth]="600"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Название</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="title" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Содержание</nz-form-label>
                    <nz-form-control>
                        <textarea nz-input formControlName="content"></textarea>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Порядок</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="number" formControlName="orderNumber" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Курс</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <nz-select *ngIf="courses.length > 0" formControlName="courseId" nzPlaceHolder="Выберите курс">
                            <nz-option *ngFor="let course of courses" [nzValue]="course.id" [nzLabel]="course.title"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="courses.length === 0" nzPlaceHolder="Загрузка курсов..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>

// frontend-react/src/components/LectureList.js
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Modal, Form, Input, InputNumber, Select, message, Spin } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { getLectures, createLecture, updateLecture, deleteLecture } from '../api/lectureApi';
import { getAllCourses } from '../api/courseApi';
import { useAuth } from '../context/AuthContext';

const { Column } = Table;
const { Option } = Select;

const LectureList = () => {
    const { user } = useAuth();
    const isAdmin = user.roles?.includes('ADMIN') || false;
    const isTeacher = user.roles?.includes('TEACHER') || false;

    const [lectures, setLectures] = useState([]);
    const [courses, setCourses] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingLecture, setEditingLecture] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        title: '',
        courseId: undefined,
        userId: user.id,
        roles: user.roles ? user.roles.join(',') : '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        const fetchCourses = async () => {
            try {
                const res = await getAllCourses();
                setCourses(res.data.content || res.data);
            } catch {
                message.error('Не удалось загрузить курсы');
            }
        };
        fetchCourses();
    }, []);

    useEffect(() => {
        fetchLectures();
    }, [queryParams]);

    const fetchLectures = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.title) delete params.title;
            if (params.courseId === undefined) delete params.courseId;
            const res = await getLectures(params);
            setLectures(res.data.content);
            setPaginationInfo({
                current: res.data.number + 1,
                pageSize: res.data.size,
                total: res.data.totalElements,
            });
        } catch {
            message.error('Не удалось загрузить лекции');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                title: value,
                page: 0,
            }));
        }, 300);
    };

    const handleFilterChange = (field, value) => {
        setQueryParams(prev => ({
            ...prev,
            [field]: value,
            page: 0,
        }));
    };

    const handleReset = () => {
        setQueryParams(prev => ({
            ...prev,
            page: 0,
            title: '',
            courseId: undefined,
        }));
    };

    const showModal = (lecture = null) => {
        setEditingLecture(lecture);
        form.resetFields();
        if (lecture) {
            form.setFieldsValue({
                title: lecture.title,
                content: lecture.content,
                orderNumber: lecture.orderNumber !== undefined ? Number(lecture.orderNumber) : undefined,
                courseId: lecture.course?.id,
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingLecture) {
                await updateLecture(editingLecture.id, values);
                message.success('Лекция обновлена');
            } else {
                await createLecture(values);
                message.success('Лекция создана');
            }
            setModalVisible(false);
            fetchLectures();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить лекцию?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteLecture(id);
                    message.success('Лекция удалена');
                    fetchLectures();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    const canEdit = (lecture) => {
        return isAdmin || (isTeacher && lecture.course?.teacher?.id === user.id);
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space wrap>
                        <Input
                            placeholder="Поиск по названию"
                            allowClear
                            value={queryParams.title}
                            onChange={handleSearchChange}
                            style={{ width: 200 }}
                        />
                        <Select
                            placeholder="Курс"
                            allowClear
                            style={{ width: 150 }}
                            value={queryParams.courseId}
                            onChange={(value) => handleFilterChange('courseId', value)}
                        >
                            {courses.map(course => (
                                <Option key={course.id} value={course.id}>{course.title}</Option>
                            ))}
                        </Select>
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    {(isAdmin || isTeacher) && (
                        <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                            Добавить лекцию
                        </Button>
                    )}
                </div>

                <Table
                    dataSource={lectures}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    {isAdmin && <Column title="ID" dataIndex="id" />}
                    <Column
                        title="Название"
                        render={(_, l) => <Link to={`/lectures/${l.id}`}>{l.title}</Link>}
                    />
                    <Column
                        title="Курс"
                        render={(_, l) => l.course ? <Link to={`/courses/${l.course.id}`}>{l.course.title}</Link> : '—'}
                    />
                    <Column title="Порядок" dataIndex="orderNumber" />
                    {(isAdmin || isTeacher) && (
                        <Column
                            title="Действия"
                            render={(_, lecture) => {
                                if (!canEdit(lecture)) return null;
                                return (
                                    <Space>
                                        <Button icon={<EditOutlined />} onClick={() => showModal(lecture)} />
                                        <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(lecture.id)} />
                                    </Space>
                                );
                            }}
                        />
                    )}
                </Table>

                <Modal
                    title={editingLecture ? 'Редактировать лекцию' : 'Новая лекция'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                    width={600}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="title" label="Название" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="content" label="Содержание">
                            <Input.TextArea />
                        </Form.Item>
                        <Form.Item
                            name="orderNumber"
                            label="Порядок"
                            rules={[{ type: 'number', message: 'Введите число' }]}
                        >
                            <InputNumber style={{ width: '100%' }} min={0} step={1} />
                        </Form.Item>
                        <Form.Item name="courseId" label="Курс" rules={[{ required: true }]}>
                            <Select placeholder="Выберите курс">
                                {courses.map(course => (
                                    <Option key={course.id} value={course.id}>{course.title}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default LectureList;
