// frontend-angular/src/app/components/role-list/role-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RoleService } from '../../api/role.service';
import { UserService } from '../../api/user.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
    selector: 'app-role-list',
    templateUrl: './role-list.component.html',
    styleUrls: ['./role-list.component.scss']
})
export class RoleListComponent implements OnInit {
    roles: any[] = [];
    users: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchName = '';
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private roleService: RoleService,
        private userService: UserService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService
    ) {
        this.form = this.fb.group({
            name: ['', Validators.required],
            description: ['']
        });
    }

    ngOnInit(): void {
        this.loadUsers();
        this.loadRoles();
    }

    loadUsers(): void {
        this.userService.getAllUsers().subscribe({
            next: (res) => {
                this.users = Array.isArray(res) ? res : res.content || [];
            },
            error: () => this.message.error('Не удалось загрузить пользователей')
        });
    }

    loadRoles(): void {
        this.loading = true;
        const params = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            name: this.searchName || undefined
        };
        this.roleService.getRoles(params).subscribe({
            next: (res) => {
                this.roles = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить роли');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadRoles();
    }

    resetSearch(): void {
        this.searchName = '';
        this.pageIndex = 1;
        this.loadRoles();
    }

    getUserCountForRole(roleId: number): number {
        return this.users.filter(u => u.roles.some((r: any) => r.id === roleId)).length;
    }

    showModal(data?: any): void {
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                name: data.name,
                description: data.description
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.roleService.updateRole(this.editId!, values)
            : this.roleService.createRole(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Роль обновлена' : 'Роль создана');
                this.isVisible = false;
                this.loadRoles();
            },
            error: (err) => {
                if (err.status === 409) {
                    this.message.error('Роль с таким названием уже существует');
                } else {
                    this.message.error(err.error?.message || 'Ошибка сохранения');
                }
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteRole(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить роль?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOnOk: () => {
                this.roleService.deleteRole(id).subscribe({
                    next: () => {
                        this.message.success('Роль удалена');
                        this.loadRoles();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    isAdmin(): boolean {
        return this.auth.isAdmin();
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchName = value;
            this.pageIndex = 1;
            this.loadRoles();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию" [(ngModel)]="searchName" (ngModelChange)="onSearchChange($event)" style="width:250px;" />
        <button nz-button (click)="resetSearch()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="isAdmin()" (click)="showModal()" class="add-btn">Добавить роль</button>
    </div>

    <nz-table
            [nzData]="roles"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="isAdmin()">ID</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Пользователей</th>
            <th *ngIf="isAdmin()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let role of roles">
            <td *ngIf="isAdmin()">{{ role.id }}</td>
            <td><a [routerLink]="['/roles', role.id]">{{ role.name }}</a></td>
            <td>{{ role.description }}</td>
            <td>{{ getUserCountForRole(role.id) }}</td>
            <td *ngIf="isAdmin()">
                <button nz-button nzType="link" (click)="showModal(role)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger (click)="deleteRole(role.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать роль' : 'Новая роль'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Название</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="name" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Описание</nz-form-label>
                    <nz-form-control>
                        <textarea nz-input formControlName="description"></textarea>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>

// frontend-react/src/components/RoleList.js
import React, { useState, useEffect, useRef } from 'react';
import {
    Table, Button, Space, Modal, Form, Input, message, Spin
} from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { getRoles, createRole, updateRole, deleteRole } from '../api/roleApi';
import { getAllUsers } from '../api/userApi';

const { Column } = Table;

const RoleList = () => {
    const [roles, setRoles] = useState([]);
    const [users, setUsers] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingRole, setEditingRole] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        name: '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        const fetchUsers = async () => {
            try {
                const res = await getAllUsers();
                setUsers(res.data.content || res.data);
            } catch {
                message.error('Не удалось загрузить пользователей');
            }
        };
        fetchUsers();
    }, []);

    useEffect(() => {
        fetchRoles();
    }, [queryParams]);

    const fetchRoles = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.name) delete params.name;
            const res = await getRoles(params);
            const content = res.data.content || res.data;
            setRoles(content);
            if (res.data.content) {
                setPaginationInfo({
                    current: res.data.number + 1,
                    pageSize: res.data.size,
                    total: res.data.totalElements,
                });
            } else {
                setPaginationInfo({
                    current: 1,
                    pageSize: content.length,
                    total: content.length,
                });
            }
        } catch {
            message.error('Не удалось загрузить роли');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                name: value,
                page: 0,
            }));
        }, 300);
    };

    const handleReset = () => {
        setQueryParams({
            page: 0,
            size: 10,
            name: '',
        });
    };

    const getUserCountForRole = (roleId) => {
        return users.filter(user => user.roles?.some(r => r.id === roleId)).length;
    };

    const showModal = (role = null) => {
        setEditingRole(role);
        form.resetFields();
        if (role) {
            form.setFieldsValue({
                name: role.name,
                description: role.description,
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingRole) {
                await updateRole(editingRole.id, values);
                message.success('Роль обновлена');
            } else {
                await createRole(values);
                message.success('Роль создана');
            }
            setModalVisible(false);
            fetchRoles();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else if (error.response?.status === 409) {
                message.error('Роль с таким названием уже существует');
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить роль?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteRole(id);
                    message.success('Роль удалена');
                    fetchRoles();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space>
                        <Input
                            placeholder="Поиск по названию"
                            allowClear
                            value={queryParams.name}
                            onChange={handleSearchChange}
                            style={{ width: 250 }}
                        />
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                        Добавить роль
                    </Button>
                </div>

                <Table
                    dataSource={roles}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    <Column title="ID" dataIndex="id" />
                    <Column title="Название" dataIndex="name" />
                    <Column title="Описание" dataIndex="description" />
                    <Column
                        title="Пользователей"
                        render={(_, role) => getUserCountForRole(role.id)}
                    />
                    <Column
                        title="Действия"
                        render={(_, role) => (
                            <Space>
                                <Button icon={<EditOutlined />} onClick={() => showModal(role)} />
                                <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(role.id)} />
                            </Space>
                        )}
                    />
                </Table>

                <Modal
                    title={editingRole ? 'Редактировать роль' : 'Новая роль'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="name" label="Название" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="description" label="Описание">
                            <Input.TextArea />
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default RoleList;
