// frontend-angular/src/app/components/test-list/test-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { TestService } from '../../api/test.service';
import { CourseService } from '../../api/course.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';
import { formatDateTime } from '../../utils/date-utils';

@Component({
    selector: 'app-test-list',
    templateUrl: './test-list.component.html',
    styleUrls: ['./test-list.component.scss']
})
export class TestListComponent implements OnInit {
    tests: any[] = [];
    courses: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchTitle = '';
    filterCourseId: number | null = null;
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private testService: TestService,
        private courseService: CourseService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService,
        private cdr: ChangeDetectorRef
    ) {
        this.form = this.fb.group({
            title: ['', Validators.required],
            description: [''],
            content: ['', Validators.required],
            questionsCount: [null, [Validators.required, Validators.min(1)]],
            courseId: [null, Validators.required],
            startDate: [null],
            endDate: [null],
            maxDurationMinutes: [null],
            maxAttempts: [null]
        });
    }

    ngOnInit(): void {
        this.loadCourses();
        this.loadTests();
    }

    formatDate(date: string): string {
        return formatDateTime(date);
    }

    loadCourses(): void {
        this.courseService.getAllCourses().subscribe({
            next: (res) => {
                this.courses = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить курсы')
        });
    }

    loadTests(): void {
        this.loading = true;
        const params: any = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            userId: this.auth.getUser()?.id,
            roles: this.auth.getRolesString()
        };
        if (this.searchTitle) params.title = this.searchTitle;
        if (this.filterCourseId) params.courseId = this.filterCourseId;
        this.testService.getTests(params).subscribe({
            next: (res) => {
                this.tests = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить тесты');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadTests();
    }

    resetFilters(): void {
        this.searchTitle = '';
        this.filterCourseId = null;
        this.pageIndex = 1;
        this.loadTests();
    }

    canEdit(test: any): boolean {
        return this.auth.isAdmin() || (this.auth.isTeacher() && test.course?.teacher?.id === this.auth.getUser()?.id);
    }

    canCreate(): boolean {
        return this.auth.isAdmin() || this.auth.isTeacher();
    }

    showModal(data?: any): void {
        if (this.courses.length === 0) {
            this.loadCourses();
        }
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                title: data.title,
                description: data.description,
                content: data.content,
                questionsCount: data.questionsCount,
                courseId: data.course?.id || null,
                startDate: data.startDate,
                endDate: data.endDate,
                maxDurationMinutes: data.maxDurationMinutes,
                maxAttempts: data.maxAttempts
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.testService.updateTest(this.editId!, values)
            : this.testService.createTest(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Тест обновлён' : 'Тест создан');
                this.isVisible = false;
                this.loadTests();
            },
            error: (err) => {
                this.message.error(err.error?.message || 'Ошибка сохранения');
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteTest(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить тест?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOkType: 'primary',
            nzOnOk: () => {
                this.testService.deleteTest(id).subscribe({
                    next: () => {
                        this.message.success('Тест удалён');
                        this.loadTests();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchTitle = value;
            this.pageIndex = 1;
            this.loadTests();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию" [(ngModel)]="searchTitle" (ngModelChange)="onSearchChange($event)" style="width:250px;" />
        <nz-select *ngIf="courses.length > 0" [(ngModel)]="filterCourseId" nzPlaceHolder="Курс" nzAllowClear (ngModelChange)="loadTests()" style="width:180px;">
            <nz-option *ngFor="let course of courses" [nzValue]="course.id" [nzLabel]="course.title"></nz-option>
        </nz-select>
        <nz-select *ngIf="courses.length === 0" nzPlaceHolder="Загрузка курсов..." disabled style="width:180px;"></nz-select>
        <button nz-button (click)="resetFilters()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="canCreate()" (click)="showModal()" class="add-btn">Добавить тест</button>
    </div>

    <nz-table
            [nzData]="tests"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="auth.isAdmin()">ID</th>
            <th>Название</th>
            <th>Курс</th>
            <th>Вопросов</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
            <th *ngIf="canCreate()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let test of tests">
            <td *ngIf="auth.isAdmin()">{{ test.id }}</td>
            <td><a [routerLink]="['/tests', test.id]">{{ test.title }}</a></td>
            <td><a *ngIf="test.course" [routerLink]="['/courses', test.course.id]">{{ test.course.title }}</a></td>
            <td>{{ test.questionsCount }}</td>
            <td>{{ formatDate(test.startDate) }}</td>
            <td>{{ formatDate(test.endDate) }}</td>
            <td *ngIf="canCreate()">
                <button nz-button nzType="link" *ngIf="canEdit(test)" (click)="showModal(test)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger *ngIf="canEdit(test)" (click)="deleteTest(test.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать тест' : 'Новый тест'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
            [nzWidth]="700"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Название</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="title" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Описание</nz-form-label>
                    <nz-form-control>
                        <textarea nz-input formControlName="description"></textarea>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Содержание</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <textarea nz-input formControlName="content"></textarea>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Количество вопросов</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Введите число больше 0'">
                        <input nz-input type="number" formControlName="questionsCount" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Курс</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <nz-select *ngIf="courses.length > 0" formControlName="courseId" nzPlaceHolder="Выберите курс">
                            <nz-option *ngFor="let course of courses" [nzValue]="course.id" [nzLabel]="course.title"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="courses.length === 0" nzPlaceHolder="Загрузка курсов..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Дата начала</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="datetime-local" formControlName="startDate" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Дата окончания</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="datetime-local" formControlName="endDate" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Макс. длительность (мин)</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="number" formControlName="maxDurationMinutes" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Макс. попыток</nz-form-label>
                    <nz-form-control>
                        <input nz-input type="number" formControlName="maxAttempts" />
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>

// frontend-react/src/components/TestList.js
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Modal, Form, Input, InputNumber, Select, message, Spin } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { getTests, createTest, updateTest, deleteTest } from '../api/testApi';
import { getAllCourses } from '../api/courseApi';
import { formatDateTime } from '../utils/dateUtils';
import { useAuth } from '../context/AuthContext';

const { Column } = Table;
const { Option } = Select;

const TestList = () => {
    const { user } = useAuth();
    const isAdmin = user.roles?.includes('ADMIN') || false;
    const isTeacher = user.roles?.includes('TEACHER') || false;

    const [tests, setTests] = useState([]);
    const [courses, setCourses] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingTest, setEditingTest] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        title: '',
        courseId: undefined,
        userId: user.id,
        roles: user.roles ? user.roles.join(',') : '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        const fetchCourses = async () => {
            try {
                const res = await getAllCourses();
                setCourses(res.data.content || res.data);
            } catch {
                message.error('Не удалось загрузить курсы');
            }
        };
        fetchCourses();
    }, []);

    useEffect(() => {
        fetchTests();
    }, [queryParams]);

    const fetchTests = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.title) delete params.title;
            if (params.courseId === undefined) delete params.courseId;
            const res = await getTests(params);
            setTests(res.data.content);
            setPaginationInfo({
                current: res.data.number + 1,
                pageSize: res.data.size,
                total: res.data.totalElements,
            });
        } catch {
            message.error('Не удалось загрузить тесты');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                title: value,
                page: 0,
            }));
        }, 300);
    };

    const handleFilterChange = (field, value) => {
        setQueryParams(prev => ({
            ...prev,
            [field]: value,
            page: 0,
        }));
    };

    const handleReset = () => {
        setQueryParams(prev => ({
            ...prev,
            page: 0,
            title: '',
            courseId: undefined,
        }));
    };

    const showModal = (test = null) => {
        setEditingTest(test);
        form.resetFields();
        if (test) {
            form.setFieldsValue({
                title: test.title,
                description: test.description,
                content: test.content,
                questionsCount: test.questionsCount !== undefined ? Number(test.questionsCount) : undefined,
                startDate: test.startDate,
                endDate: test.endDate,
                maxDurationMinutes: test.maxDurationMinutes,
                maxAttempts: test.maxAttempts,
                courseId: test.course?.id,
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingTest) {
                await updateTest(editingTest.id, values);
                message.success('Тест обновлён');
            } else {
                await createTest(values);
                message.success('Тест создан');
            }
            setModalVisible(false);
            fetchTests();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить тест?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteTest(id);
                    message.success('Тест удалён');
                    fetchTests();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    const canEdit = (test) => {
        return isAdmin || (isTeacher && test.course?.teacher?.id === user.id);
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space wrap>
                        <Input
                            placeholder="Поиск по названию"
                            allowClear
                            value={queryParams.title}
                            onChange={handleSearchChange}
                            style={{ width: 200 }}
                        />
                        <Select
                            placeholder="Курс"
                            allowClear
                            style={{ width: 150 }}
                            value={queryParams.courseId}
                            onChange={(value) => handleFilterChange('courseId', value)}
                        >
                            {courses.map(course => (
                                <Option key={course.id} value={course.id}>{course.title}</Option>
                            ))}
                        </Select>
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    {(isAdmin || isTeacher) && (
                        <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                            Добавить тест
                        </Button>
                    )}
                </div>

                <Table
                    dataSource={tests}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    {isAdmin && <Column title="ID" dataIndex="id" />}
                    <Column
                        title="Название"
                        render={(_, t) => <Link to={`/tests/${t.id}`}>{t.title}</Link>}
                    />
                    <Column
                        title="Курс"
                        render={(_, t) => t.course ? <Link to={`/courses/${t.course.id}`}>{t.course.title}</Link> : '—'}
                    />
                    <Column title="Вопросов" dataIndex="questionsCount" />
                    <Column title="Дата начала" render={(_, t) => formatDateTime(t.startDate)} />
                    <Column title="Дата окончания" render={(_, t) => formatDateTime(t.endDate)} />
                    {(isAdmin || isTeacher) && (
                        <Column
                            title="Действия"
                            render={(_, test) => {
                                if (!canEdit(test)) return null;
                                return (
                                    <Space>
                                        <Button icon={<EditOutlined />} onClick={() => showModal(test)} />
                                        <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(test.id)} />
                                    </Space>
                                );
                            }}
                        />
                    )}
                </Table>

                <Modal
                    title={editingTest ? 'Редактировать тест' : 'Новый тест'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                    width={700}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="title" label="Название" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="description" label="Описание">
                            <Input.TextArea />
                        </Form.Item>
                        <Form.Item name="content" label="Содержание" rules={[{ required: true }]}>
                            <Input.TextArea />
                        </Form.Item>
                        <Form.Item
                            name="questionsCount"
                            label="Количество вопросов"
                            rules={[{ required: true, type: 'number', message: 'Введите число' }]}
                        >
                            <InputNumber style={{ width: '100%' }} min={1} step={1} />
                        </Form.Item>
                        <Form.Item name="courseId" label="Курс" rules={[{ required: true }]}>
                            <Select placeholder="Выберите курс">
                                {courses.map(course => (
                                    <Option key={course.id} value={course.id}>{course.title}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                        <Form.Item name="startDate" label="Дата начала">
                            <Input placeholder="YYYY-MM-DDTHH:mm:ss" />
                        </Form.Item>
                        <Form.Item name="endDate" label="Дата окончания">
                            <Input placeholder="YYYY-MM-DDTHH:mm:ss" />
                        </Form.Item>
                        <Form.Item name="maxDurationMinutes" label="Макс. длительность (мин)">
                            <InputNumber style={{ width: '100%' }} min={0} step={1} />
                        </Form.Item>
                        <Form.Item name="maxAttempts" label="Макс. попыток">
                            <InputNumber style={{ width: '100%' }} min={1} step={1} />
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default TestList;
