// frontend-react/src/pages/CategoryDetailPage.jsx
import React, { useEffect, useState } from 'react';
import {useParams, useNavigate, Link} from 'react-router-dom';
import { getCategoryById } from '../api/categoryApi';
import { getCourses } from '../api/courseApi';
import { useAuth } from '../context/AuthContext';
import { Button, List, Card, Typography, Spin } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';

const { Title } = Typography;

const CategoryDetailPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const [category, setCategory] = useState(null);
    const [courses, setCourses] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchData = async () => {
            setLoading(true);
            try {
                const [catRes, coursesRes] = await Promise.all([
                    getCategoryById(id),
                    getCourses({
                        categoryId: id,
                        userId: user.id,
                        roles: user.roles,
                        size: 100,
                    }),
                ]);
                setCategory(catRes.data);
                setCourses(coursesRes.data.content);
            } catch (error) {
                console.error(error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [id, user]);

    if (loading) return <Spin tip="Загрузка..." />;
    if (!category) return <div>Категория не найдена</div>;

    return (
        <div>
            <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)} style={{ marginBottom: 16 }}>
                Назад
            </Button>
            <Title level={2}>{category.name}</Title>
            <p>{category.description}</p>
            <Title level={4}>Курсы в этой категории</Title>
            {courses.length === 0 ? (
                <p>В этой категории нет курсов</p>
            ) : (
                <List
                    grid={{ gutter: 16, column: 3 }}
                    dataSource={courses}
                    renderItem={course => (
                        <List.Item>
                            <Card
                                hoverable
                                onClick={() => navigate(`/courses/${course.id}`)}
                                title={<Link to={`/courses/${course.id}`}>{course.title}</Link>}
                            >
                                {course.description}
                            </Card>
                        </List.Item>
                    )}
                />
            )}
        </div>
    );
};

export default CategoryDetailPage;

// frontend-angular/src/app/pages/category-detail-page/category-detail-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CategoryService } from '../../api/category.service';
import { CourseService } from '../../api/course.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Location } from "@angular/common";

@Component({
    selector: 'app-category-detail-page',
    templateUrl: './category-detail-page.component.html',
    styleUrls: ['./category-detail-page.component.scss']
})
export class CategoryDetailPageComponent implements OnInit {
    category: any = null;
    courses: any[] = [];
    loading = true;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private categoryService: CategoryService,
        private courseService: CourseService,
        public  auth: AuthService,
        private message: NzMessageService,
        private location: Location
    ) {}

    ngOnInit(): void {
        const id = Number(this.route.snapshot.paramMap.get('id'));
        if (id) {
            this.loadData(id);
        }
    }

    loadData(categoryId: number): void {
        this.loading = true;
        this.categoryService.getCategoryById(categoryId).subscribe({
            next: (cat) => {
                this.category = cat;
                const params = {
                    categoryId,
                    userId: this.auth.getUser()?.id,
                    roles: this.auth.getRolesString(),
                    size: 100
                };
                this.courseService.getCourses(params).subscribe({
                    next: (res) => {
                        this.courses = res.content || [];
                        this.loading = false;
                    },
                    error: () => {
                        this.message.error('Не удалось загрузить курсы');
                        this.loading = false;
                    }
                });
            },
            error: () => {
                this.message.error('Не удалось загрузить категорию');
                this.loading = false;
            }
        });
    }

    goBack(): void {
        this.location.back();
    }

    navigateToCourse(id: number): void {
        this.router.navigate(['/courses', id]);
    }
}
<div class="container">
    <button nz-button nzType="default" (click)="goBack()" style="margin-bottom:16px;">
        <i nz-icon nzType="arrow-left"></i> Назад
    </button>
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="category">
            <h2>{{ category.name }}</h2>
            <p>{{ category.description }}</p>
            <h4>Курсы в этой категории</h4>
            <nz-list *ngIf="courses.length > 0; else noCourses" [nzGrid]="{ gutter: 16, column: 3 }">
                <nz-list-item *ngFor="let course of courses">
                    <nz-card [nzTitle]="course.title" (click)="navigateToCourse(course.id)" nzHoverable>
                        {{ course.description }}
                    </nz-card>
                </nz-list-item>
            </nz-list>
            <ng-template #noCourses><p>В этой категории нет курсов</p></ng-template>
        </div>
    </nz-spin>
</div>
