// frontend-react/src/components/UserList.js
import React, { useState, useEffect, useRef } from 'react';
import {
    Table, Button, Space, Modal, Form, Input, Select, Tag, message, Spin
} from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { getUsers, createUser, updateUser, deleteUser } from '../api/userApi';
import { getAllRoles } from '../api/roleApi';

const { Column } = Table;
const { Option } = Select;

const UserList = () => {
    const [users, setUsers] = useState([]);
    const [roles, setRoles] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingUser, setEditingUser] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        username: '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        fetchUsers();
    }, [queryParams]);

    useEffect(() => {
        const fetchRoles = async () => {
            try {
                const res = await getAllRoles();
                setRoles(res.data.content || res.data);
            } catch {
                message.error('Не удалось загрузить роли');
            }
        };
        fetchRoles();
    }, []);

    const fetchUsers = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.username) delete params.username;
            const res = await getUsers(params);
            setUsers(res.data.content);
            setPaginationInfo({
                current: res.data.number + 1,
                pageSize: res.data.size,
                total: res.data.totalElements,
            });
        } catch {
            message.error('Не удалось загрузить пользователей');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                username: value,
                page: 0,
            }));
        }, 300);
    };

    const handleReset = () => {
        setQueryParams({
            page: 0,
            size: 10,
            username: '',
        });
    };

    const showModal = (user = null) => {
        setEditingUser(user);
        form.resetFields();
        if (user) {
            form.setFieldsValue({
                username: user.username,
                email: user.email,
                fullName: user.fullName,
                roleIds: user.roles?.map(r => r.id) || [],
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingUser) {
                await updateUser(editingUser.id, values);
                message.success('Пользователь обновлён');
            } else {
                await createUser(values);
                message.success('Пользователь создан');
            }
            setModalVisible(false);
            fetchUsers();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить пользователя?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteUser(id);
                    message.success('Пользователь удалён');
                    fetchUsers();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space>
                        <Input
                            placeholder="Поиск по логину"
                            allowClear
                            value={queryParams.username}
                            onChange={handleSearchChange}
                            style={{ width: 250 }}
                        />
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                        Добавить пользователя
                    </Button>
                </div>

                <Table
                    dataSource={users}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    <Column title="ID" dataIndex="id" />
                    <Column title="Логин" dataIndex="username" />
                    <Column title="Email" dataIndex="email" />
                    <Column title="Полное имя" dataIndex="fullName" />
                    <Column
                        title="Роли"
                        render={(_, user) => (
                            <Space wrap>
                                {user.roles?.map(role => (
                                    <Tag key={role.id} color="blue">{role.name}</Tag>
                                )) || '—'}
                            </Space>
                        )}
                    />
                    <Column
                        title="Действия"
                        render={(_, user) => (
                            <Space>
                                <Button icon={<EditOutlined />} onClick={() => showModal(user)} />
                                <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(user.id)} />
                            </Space>
                        )}
                    />
                </Table>

                <Modal
                    title={editingUser ? 'Редактировать пользователя' : 'Новый пользователь'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                    width={600}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="username" label="Логин" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="email" label="Email" rules={[{ required: true, type: 'email' }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item
                            name="password"
                            label="Пароль"
                            rules={[
                                { required: !editingUser, message: 'Введите пароль' },
                                { min: 6, message: 'Минимум 6 символов' }
                            ]}
                        >
                            <Input.Password placeholder={editingUser ? 'Оставьте пустым, чтобы не менять' : ''} />
                        </Form.Item>
                        <Form.Item name="fullName" label="Полное имя">
                            <Input />
                        </Form.Item>
                        <Form.Item name="roleIds" label="Роли">
                            <Select mode="multiple" placeholder="Выберите роли">
                                {roles.map(role => (
                                    <Option key={role.id} value={role.id}>{role.name}</Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default UserList;

// frontend-angular/src/app/components/user-list/user-list.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from '../../api/user.service';
import { RoleService } from '../../api/role.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
    selector: 'app-user-list',
    templateUrl: './user-list.component.html',
    styleUrls: ['./user-list.component.scss']
})
export class UserListComponent implements OnInit {
    users: any[] = [];
    roles: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchUsername = '';
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private userService: UserService,
        private roleService: RoleService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService,
        private cdr: ChangeDetectorRef
    ) {
        this.form = this.fb.group({
            username: ['', Validators.required],
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.minLength(6)]],
            fullName: [''],
            roleIds: [[]]
        });
    }

    ngOnInit(): void {
        this.loadUsers();
        this.loadRoles();
    }

    loadUsers(): void {
        this.loading = true;
        const params = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            username: this.searchUsername || undefined
        };
        this.userService.getUsers(params).subscribe({
            next: (res) => {
                this.users = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить пользователей');
                this.loading = false;
            }
        });
    }

    loadRoles(): void {
        this.roleService.getAllRoles().subscribe({
            next: (res) => {
                this.roles = Array.isArray(res) ? res : res.content || [];
                this.cdr.detectChanges();
            },
            error: () => this.message.error('Не удалось загрузить роли')
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadUsers();
    }

    resetSearch(): void {
        this.searchUsername = '';
        this.pageIndex = 1;
        this.loadUsers();
    }

    showModal(data?: any): void {
        if (this.roles.length === 0) {
            this.loadRoles();
        }
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                username: data.username,
                email: data.email,
                fullName: data.fullName,
                roleIds: data.roles.map((r: any) => r.id)
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.userService.updateUser(this.editId!, values)
            : this.userService.createUser(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Пользователь обновлён' : 'Пользователь создан');
                this.isVisible = false;
                this.loadUsers();
            },
            error: (err) => {
                const msg = err.error?.message || 'Ошибка сохранения';
                this.message.error(msg);
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteUser(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить пользователя?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOnOk: () => {
                this.userService.deleteUser(id).subscribe({
                    next: () => {
                        this.message.success('Пользователь удалён');
                        this.loadUsers();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    isAdmin(): boolean {
        return this.auth.isAdmin();
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchUsername = value;
            this.pageIndex = 1;
            this.loadUsers();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по логину" [(ngModel)]="searchUsername" (ngModelChange)="onSearchChange($event)" style="width:250px;" />
        <button nz-button (click)="resetSearch()">Сбросить</button>
        <button nz-button nzType="primary" (click)="showModal()" class="add-btn">Добавить пользователя</button>
    </div>

    <nz-table
            [nzData]="users"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="isAdmin()">ID</th>
            <th>Логин</th>
            <th>Email</th>
            <th>Полное имя</th>
            <th>Роли</th>
            <th *ngIf="isAdmin()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let user of users">
            <td *ngIf="isAdmin()">{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.fullName }}</td>
            <td>
                <nz-tag *ngFor="let role of user.roles" nzColor="blue" [routerLink]="['/roles', role.id]">{{ role.name }}</nz-tag>
            </td>
            <td *ngIf="isAdmin()">
                <button nz-button nzType="link" (click)="showModal(user)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger (click)="deleteUser(user.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать пользователя' : 'Новый пользователь'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Логин</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="username" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Email</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Введите корректный email'">
                        <input nz-input formControlName="email" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item *ngIf="!isEdit">
                    <nz-form-label>Пароль</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Минимум 6 символов'">
                        <input nz-input type="password" formControlName="password" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Полное имя</nz-form-label>
                    <nz-form-control>
                        <input nz-input formControlName="fullName" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Роли</nz-form-label>
                    <nz-form-control>
                        <nz-select *ngIf="roles.length > 0" formControlName="roleIds" nzMode="multiple" nzPlaceHolder="Выберите роли">
                            <nz-option *ngFor="let role of roles" [nzValue]="role.id" [nzLabel]="role.name"></nz-option>
                        </nz-select>
                        <nz-select *ngIf="roles.length === 0" nzPlaceHolder="Загрузка ролей..." disabled></nz-select>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>
