// frontend-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './api/auth.service';
import { Router } from '@angular/router';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    constructor(public auth: AuthService, private router: Router) {}

    logout(): void {
        this.auth.logout();
        this.router.navigate(['/login']);
    }
}
<nz-layout *ngIf="auth.getUser(); else loginTemplate">
    <nz-header>
        <div class="logo">
            <a routerLink="/">
                <img src="/favicon.ico" alt="LMS" style="height:28px;margin-right:10px" />
                <span style="color:#fff;font-size:20px">LMS</span>
            </a>
        </div>
        <ul nz-menu nzTheme="dark" nzMode="horizontal">
            <li nz-menu-item routerLink="/" routerLinkActive="ant-menu-item-selected" [routerLinkActiveOptions]="{exact: true}">
                <i nz-icon nzType="home"></i>Главная
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin()" routerLink="/users" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="user"></i>Пользователи
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin()" routerLink="/roles" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="team"></i>Роли
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin() || auth.isTeacher()" routerLink="/categories" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="appstore"></i>Категории
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin() || auth.isTeacher()" routerLink="/courses" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="book"></i>Курсы
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin() || auth.isTeacher()" routerLink="/lectures" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="file-text"></i>Лекции
            </li>
            <li nz-menu-item *ngIf="auth.isAdmin() || auth.isTeacher()" routerLink="/tests" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="check-circle"></i>Тесты
            </li>
            <li nz-menu-item routerLink="/attempts" routerLinkActive="ant-menu-item-selected">
                <i nz-icon nzType="solution"></i>Попытки
            </li>
        </ul>
        <div class="user-info">
            <span>{{ auth.getUser()?.username }} ({{ auth.getUser()?.roleDescription }})</span>
            <button nz-button nzType="link" (click)="logout()" style="color:#fff">Выйти</button>
        </div>
    </nz-header>
    <nz-content>
        <router-outlet></router-outlet>
    </nz-content>
</nz-layout>
<ng-template #loginTemplate>
    <router-outlet></router-outlet>
</ng-template>

// frontend-react/src/App.js
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link, useLocation, Navigate } from 'react-router-dom';
import { Layout, Menu, Button } from 'antd';
import {
    UserOutlined,
    TeamOutlined,
    AppstoreOutlined,
    BookOutlined,
    FileTextOutlined,
    CheckCircleOutlined,
    SolutionOutlined,
} from '@ant-design/icons';
import { useAuth, AuthProvider } from './context/AuthContext';
import LoginPage from './pages/LoginPage';
import UserList from './components/UserList';
import RoleList from './components/RoleList';
import CategoryList from './components/CategoryList';
import CourseList from './components/CourseList';
import LectureList from './components/LectureList';
import TestList from './components/TestList';
import TestAttemptList from './components/TestAttemptList';
import './App.css';

const { Header, Content } = Layout;

const AppContent = () => {
    const { user, logout } = useAuth();
    const location = useLocation();
    const currentKey = location.pathname.slice(1) || 'courses';

    if (!user) {
        return <Navigate to="/login" />;
    }

    const isAdmin = user.roles?.includes('ADMIN') || false;
    const isTeacher = user.roles?.includes('TEACHER') || false;

    return (
        <Layout style={{ minHeight: '100vh' }}>
            <Header style={{display: 'flex', alignItems: 'center'}}>
                <img src="/favicon.ico" alt="LMS" style={{height: 28, marginRight: 10}}/>
                <div style={{color: '#fff', fontSize: 20, marginRight: 40}}>LMS</div>
                <Menu
                    theme="dark"
                    mode="horizontal"
                    selectedKeys={[currentKey]}
                    style={{flex: 1, minWidth: 0}}
                >
                    {isAdmin && (
                        <>
                            <Menu.Item key="users" icon={<UserOutlined/>}>
                                <Link to="/users">Пользователи</Link>
                            </Menu.Item>
                            <Menu.Item key="roles" icon={<TeamOutlined/>}>
                                <Link to="/roles">Роли</Link>
                            </Menu.Item>
                        </>
                    )}
                    <Menu.Item key="categories" icon={<AppstoreOutlined/>}>
                        <Link to="/categories">Категории</Link>
                    </Menu.Item>
                    <Menu.Item key="courses" icon={<BookOutlined/>}>
                        <Link to="/courses">Курсы</Link>
                    </Menu.Item>
                    <Menu.Item key="lectures" icon={<FileTextOutlined/>}>
                        <Link to="/lectures">Лекции</Link>
                    </Menu.Item>
                    <Menu.Item key="tests" icon={<CheckCircleOutlined/>}>
                        <Link to="/tests">Тесты</Link>
                    </Menu.Item>
                    <Menu.Item key="attempts" icon={<SolutionOutlined/>}>
                        <Link to="/attempts">Попытки</Link>
                    </Menu.Item>
                </Menu>
                <div style={{marginLeft: 'auto', color: '#fff'}}>
                    <span style={{marginRight: 16}}>{user.username} ({user.roleDescription})</span>
                    <Button type="link" onClick={logout} style={{color: '#fff'}}>Выйти</Button>
                </div>
            </Header>
            <Content style={{padding: '24px 24px'}}>
                <Routes>
                    <Route path="/users" element={<UserList/>}/>
                    <Route path="/roles" element={<RoleList/>}/>
                    <Route path="/categories" element={<CategoryList />} />
                    <Route path="/courses" element={<CourseList />} />
                    <Route path="/lectures" element={<LectureList />} />
                    <Route path="/tests" element={<TestList />} />
                    <Route path="/attempts" element={<TestAttemptList />} />
                    <Route path="/" element={<CourseList />} />
                </Routes>
            </Content>
        </Layout>
    );
};

const App = () => {
    return (
        <Router>
            <AuthProvider>
                <Routes>
                    <Route path="/login" element={<LoginPage />} />
                    <Route path="/*" element={<AppContent />} />
                </Routes>
            </AuthProvider>
        </Router>
    );
};

export default App;
