// frontend-angular/src/app/pages/course-detail-page/course-detail-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CourseService } from '../../api/course.service';
import { LectureService } from '../../api/lecture.service';
import { TestService } from '../../api/test.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Location } from "@angular/common";

@Component({
    selector: 'app-course-detail-page',
    templateUrl: './course-detail-page.component.html',
    styleUrls: ['./course-detail-page.component.scss']
})
export class CourseDetailPageComponent implements OnInit {
    course: any = null;
    lectures: any[] = [];
    tests: any[] = [];
    loading = true;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private courseService: CourseService,
        private lectureService: LectureService,
        private testService: TestService,
        public  auth: AuthService,
        private message: NzMessageService,
        private location: Location
    ) {}

    ngOnInit(): void {
        const id = Number(this.route.snapshot.paramMap.get('id'));
        if (id) {
            this.loadData(id);
        }
    }

    loadData(courseId: number): void {
        this.loading = true;
        const userId = this.auth.getUser()?.id;
        const roles = this.auth.getRolesString();
        const params = { userId, roles, size: 100 };

        this.courseService.getCourseById(courseId).subscribe({
            next: (course) => {
                this.course = course;
                // load lectures
                this.lectureService.getLectures({ ...params, courseId }).subscribe({
                    next: (res) => { this.lectures = res.content || []; },
                    error: () => this.message.error('Не удалось загрузить лекции')
                });
                this.testService.getTests({ ...params, courseId }).subscribe({
                    next: (res) => { this.tests = res.content || []; },
                    error: () => this.message.error('Не удалось загрузить тесты')
                });
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить курс');
                this.loading = false;
            }
        });
    }

    goBack(): void {
        this.location.back();
    }
}
<div class="container">
    <div class="back-row">
        <button nz-button nzType="default" (click)="goBack()">
            <i nz-icon nzType="arrow-left"></i> Назад
        </button>
        <hr class="flex-divider" />
    </div>
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="course">
            <h2>{{ course.title }}</h2>
            <p><strong>Преподаватель:</strong> {{ course.teacher?.fullName || 'Не указан' }}</p>
            <p>{{ course.description }}</p>

            <h4>Лекции</h4>
            <nz-list *ngIf="lectures.length > 0; else noLectures">
                <nz-list-item *ngFor="let lecture of lectures">
                    <a [routerLink]="['/lectures', lecture.id]">{{ lecture.title }}</a>
                </nz-list-item>
            </nz-list>
            <ng-template #noLectures><p>Нет лекций</p></ng-template>

            <h4>Тесты</h4>
            <nz-list *ngIf="tests.length > 0; else noTests">
                <nz-list-item *ngFor="let test of tests">
                    <a [routerLink]="['/tests', test.id]">{{ test.title }}</a>
                </nz-list-item>
            </nz-list>
            <ng-template #noTests><p>Нет тестов</p></ng-template>
        </div>
    </nz-spin>
</div>

// frontend-react/src/pages/CourseDetailPage.jsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getCourseById } from '../api/courseApi';
import { getLectures } from '../api/lectureApi';
import { getTests } from '../api/testApi';
import { useAuth } from '../context/AuthContext';
import { Button, List, Typography, Spin, message } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';

const { Title } = Typography;

const CourseDetailPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const [course, setCourse] = useState(null);
    const [lectures, setLectures] = useState([]);
    const [tests, setTests] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchData = async () => {
            setLoading(true);
            try {
                const [courseRes, lecturesRes, testsRes] = await Promise.all([
                    getCourseById(id),
                    getLectures({ courseId: id, userId: user.id, roles: user.roles, size: 100 }),
                    getTests({ courseId: id, userId: user.id, roles: user.roles, size: 100 }),
                ]);
                setCourse(courseRes.data);
                setLectures(lecturesRes?.data?.content || []);
                setTests(testsRes?.data?.content || []);
            } catch (error) {
                console.error(error);
                message.error('Не удалось загрузить данные курса');
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [id, user]);

    if (loading) return <Spin tip="Загрузка..." />;
    if (!course) return <div>Курс не найден</div>;

    return (
        <div>
            <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)} style={{ marginBottom: 16 }}>
                Назад
            </Button>
            <Title level={2}>{course.title}</Title>
            <p><strong>Преподаватель:</strong> {course.teacher?.fullName || 'Не указан'}</p>
            <p>{course.description}</p>

            <Title level={4}>Лекции</Title>
            {lectures.length === 0 ? (
                <p>Нет лекций</p>
            ) : (
                <List
                    dataSource={lectures}
                    renderItem={lecture => (
                        <List.Item>
                            <Link to={`/lectures/${lecture.id}`}>{lecture.title}</Link>
                        </List.Item>
                    )}
                />
            )}

            <Title level={4}>Тесты</Title>
            {tests.length === 0 ? (
                <p>Нет тестов</p>
            ) : (
                <List
                    dataSource={tests}
                    renderItem={test => (
                        <List.Item>
                            <Link to={`/tests/${test.id}`}>{test.title}</Link>
                        </List.Item>
                    )}
                />
            )}
        </div>
    );
};

export default CourseDetailPage;
