// frontend-angular/src/app/pages/role-detail-page/role-detail-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { RoleService } from '../../api/role.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Location } from "@angular/common";

@Component({
    selector: 'app-role-detail-page',
    templateUrl: './role-detail-page.component.html',
    styleUrls: ['./role-detail-page.component.scss']
})
export class RoleDetailPageComponent implements OnInit {
    role: any = null;
    users: any[] = [];
    loading = true;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private roleService: RoleService,
        private message: NzMessageService,
        private location: Location
    ) {}

    ngOnInit(): void {
        const id = Number(this.route.snapshot.paramMap.get('id'));
        if (id) {
            this.loadData(id);
        }
    }

    loadData(roleId: number): void {
        this.loading = true;
        this.roleService.getRoleById(roleId).subscribe({
            next: (role) => {
                this.role = role;
                this.roleService.getUsersByRole(roleId).subscribe({
                    next: (users) => {
                        this.users = users;
                        this.loading = false;
                    },
                    error: () => {
                        this.message.error('Не удалось загрузить пользователей');
                        this.loading = false;
                    }
                });
            },
            error: () => {
                this.message.error('Не удалось загрузить роль');
                this.loading = false;
            }
        });
    }

    goBack(): void {
        this.location.back();
    }
}
<div class="container">
    <div class="back-row">
        <button nz-button nzType="default" (click)="goBack()">
            <i nz-icon nzType="arrow-left"></i> Назад
        </button>
        <hr class="flex-divider" />
    </div>
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="role">
            <h2>Роль: {{ role.name }}</h2>
            <p>{{ role.description }}</p>
            <h4>Пользователи с этой ролью ({{ users.length }})</h4>
            <nz-list *ngIf="users.length > 0; else noUsers">
                <nz-list-item *ngFor="let user of users; let i = index">
                    {{ i + 1 }}. {{ user.username }} ({{ user.fullName || user.username }})
                </nz-list-item>
            </nz-list>
            <ng-template #noUsers><p>Нет пользователей</p></ng-template>
        </div>
    </nz-spin>
</div>

// frontend-react/src/pages/RoleDetailPage.jsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getRoleById, getUsersByRole } from '../api/roleApi';
import { Button, Typography, List, Spin } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';

const { Title } = Typography;

const RoleDetailPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [role, setRole] = useState(null);
    const [users, setUsers] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchData = async () => {
            setLoading(true);
            try {
                const [roleRes, usersRes] = await Promise.all([
                    getRoleById(id),
                    getUsersByRole(id),
                ]);
                setRole(roleRes.data);
                setUsers(usersRes.data);
            } catch (error) {
                console.error(error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [id]);

    if (loading) return <Spin tip="Загрузка..." />;
    if (!role) return <div>Роль не найдена</div>;

    return (
        <div>
            <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)} style={{ marginBottom: 16 }}>
                Назад
            </Button>
            <Title level={2}>Роль: {role.name}</Title>
            <p>{role.description}</p>
            <Title level={4}>
                Пользователи с этой ролью ({users.length})
            </Title>
            {users.length === 0 ? (
                <p>Нет пользователей</p>
            ) : (
                <List
                    dataSource={users}
                    renderItem={(user, index) => (
                        <List.Item>
                            {index + 1}. {user.username} ({user.fullName || user.username})
                        </List.Item>
                    )}
                />
            )}
        </div>
    );
};

export default RoleDetailPage;
