// frontend-angular/src/app/pages/test-pass-page/test-pass-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { TestService } from '../../api/test.service';
import { TestAttemptService } from '../../api/test-attempt.service';
import { AuthService } from '../../api/auth.service';
import { parseGift, GiftQuestion } from '../../utils/gift-parser';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Location } from '@angular/common';

@Component({
    selector: 'app-test-pass-page',
    templateUrl: './test-pass-page.component.html',
    styleUrls: ['./test-pass-page.component.scss']
})
export class TestPassPageComponent implements OnInit {
    test: any = null;
    questions: GiftQuestion[] = [];
    answers: { [key: number]: any } = {};
    currentIndex = 0;
    loading = true;
    submitting = false;
    attemptId: number | null = null;
    testId: number = 0;

    // Для чекбоксов будем хранить отдельно массивы выбранных значений
    // Но можно и так: answers уже хранит массив выбранных текстов.

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private testService: TestService,
        private testAttemptService: TestAttemptService,
        public auth: AuthService,
        private message: NzMessageService,
        private location: Location
    ) {}

    ngOnInit(): void {
        this.testId = Number(this.route.snapshot.paramMap.get('id'));
        if (this.testId) {
            this.initTest();
        }
    }

    initTest(): void {
        this.loading = true;
        const userId = this.auth.getUser()?.id;
        const roles = this.auth.getRolesString();

        this.testService.getTestById(this.testId).subscribe({
            next: (test) => {
                this.test = test;
                const parsed = parseGift(test.content);
                this.questions = parsed;
                this.answers = {};
                this.questions.forEach((q, idx) => {
                    if (q.type === 'short' || q.type === 'numeric' || q.type === 'essay') {
                        this.answers[idx] = '';
                    } else if (q.type === 'choice') {
                        this.answers[idx] = null;
                    } else if (q.type === 'multi') {
                        this.answers[idx] = [];
                    }
                });
                this.loadAttempt();
            },
            error: () => {
                this.message.error('Ошибка загрузки теста');
                this.loading = false;
            }
        });
    }

    loadAttempt(): void {
        const userId = this.auth.getUser()?.id;
        const roles = this.auth.getRolesString();

        this.testAttemptService.getTestAttempts({
            testId: this.testId,
            userId,
            currentUserId: userId,
            roles,
            size: 10000
        }).subscribe({
            next: (res) => {
                const attempts = res.content || [];
                const inProgress = attempts.find((a: any) => a.status === 'IN_PROGRESS');
                if (inProgress) {
                    this.attemptId = inProgress.id;
                    this.message.info('Продолжаем предыдущую попытку');
                    this.loading = false;
                } else {
                    const attemptNumber = attempts.length > 0 ? Math.max(...attempts.map((a: any) => a.attemptNumber)) + 1 : 1;
                    const attemptData = {
                        testId: this.testId,
                        userId,
                        attemptNumber,
                        startTime: new Date().toISOString(),
                        endTime: null,
                        score: null,
                        status: 'IN_PROGRESS'
                    };
                    this.testAttemptService.createTestAttempt(attemptData).subscribe({
                        next: (created) => {
                            this.attemptId = created.id;
                            this.message.success('Начат новый тест');
                            this.loading = false;
                        },
                        error: (err) => {
                            if (err.status === 409 || err.error?.message?.includes('duplicate')) {
                                this.retryFetchAttempt();
                            } else {
                                this.message.error('Не удалось создать попытку');
                                this.loading = false;
                            }
                        }
                    });
                }
            },
            error: () => {
                this.message.error('Ошибка загрузки попыток');
                this.loading = false;
            }
        });
    }

    retryFetchAttempt(): void {
        const userId = this.auth.getUser()?.id;
        const roles = this.auth.getRolesString();
        this.testAttemptService.getTestAttempts({
            testId: this.testId,
            userId,
            currentUserId: userId,
            roles,
            size: 10000
        }).subscribe({
            next: (retryRes) => {
                const all = retryRes.content || [];
                const existing = all.find((a: any) => a.status === 'IN_PROGRESS');
                if (existing) {
                    this.attemptId = existing.id;
                    this.message.info('Продолжаем предыдущую попытку');
                    this.loading = false;
                } else {
                    this.message.error('Не удалось создать попытку: конфликт');
                    this.loading = false;
                }
            },
            error: () => {
                this.message.error('Ошибка загрузки попытки');
                this.loading = false;
            }
        });
    }

    get currentQuestion(): GiftQuestion | null {
        return this.questions[this.currentIndex] || null;
    }

    get progressPercent(): number {
        if (this.questions.length === 0) return 0;
        return Math.round((this.currentIndex + 1) / this.questions.length * 100);
    }

    onAnswerChange(value: any): void {
        this.answers[this.currentIndex] = value;
    }

    onMultiChange(value: any, checked: boolean): void {
        const current = this.answers[this.currentIndex] || [];
        if (checked) {
            current.push(value);
        } else {
            const index = current.indexOf(value);
            if (index !== -1) current.splice(index, 1);
        }
        this.answers[this.currentIndex] = current;
    }

    isChecked(optionText: string): boolean {
        return (this.answers[this.currentIndex] || []).includes(optionText);
    }

    onShortChange(event: Event): void {
        const input = event.target as HTMLInputElement;
        this.answers[this.currentIndex] = input.value;
    }

    prevQuestion(): void {
        if (this.currentIndex > 0) this.currentIndex--;
    }

    nextQuestion(): void {
        if (this.currentIndex < this.questions.length - 1) this.currentIndex++;
    }

    submitTest(): void {
        let correctCount = 0;
        const totalQuestions = this.questions.length;
        this.questions.forEach((q, idx) => {
            const userAnswer = this.answers[idx];
            if (q.type === 'choice') {
                const correctOption = q.options?.find(opt => opt.correct);
                if (correctOption && userAnswer === correctOption.text) correctCount++;
            } else if (q.type === 'multi') {
                const correctOptions = q.options?.filter(opt => opt.correct).map(opt => opt.text) || [];
                const userOptions = userAnswer || [];
                const sortedCorrect = [...correctOptions].sort();
                const sortedUser = [...userOptions].sort();
                if (JSON.stringify(sortedCorrect) === JSON.stringify(sortedUser)) correctCount++;
            } else if (q.type === 'short' || q.type === 'numeric') {
                if (q.correct && userAnswer && userAnswer.trim().toLowerCase() === q.correct.toLowerCase()) correctCount++;
            } else if (q.type === 'essay') {
                if (userAnswer && userAnswer.trim() !== '') correctCount++;
            }
        });
        const score = Math.round((correctCount / totalQuestions) * 100);

        this.submitting = true;
        this.testAttemptService.updateTestAttempt(this.attemptId!, {
            endTime: new Date().toISOString(),
            score: score,
            status: 'COMPLETED'
        }).subscribe({
            next: () => {
                this.message.success(`Тест завершён! Вы набрали ${score}%`);
                this.router.navigate(['/tests', this.testId]);
            },
            error: () => {
                this.message.error('Ошибка сохранения результатов');
                this.submitting = false;
            }
        });
    }

    toggleOption(optionText: string): void {
        const current = this.answers[this.currentIndex] || [];
        const index = current.indexOf(optionText);
        if (index === -1) {
            current.push(optionText);
        } else {
            current.splice(index, 1);
        }
        this.answers[this.currentIndex] = [...current];
    }
}
<div class="container">
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="test && questions.length > 0">
            <h2>{{ test.title }}</h2>
            <p>{{ test.description }}</p>
            <nz-divider></nz-divider>
            <div style="margin-bottom:16px;">
                <strong>Вопрос {{ currentIndex + 1 }} из {{ questions.length }}</strong>
            </div>
            <nz-card>
                <p><strong>{{ currentQuestion?.question }}</strong></p>

                <nz-radio-group *ngIf="currentQuestion?.type === 'choice'" [(ngModel)]="answers[currentIndex]" style="display: flex; flex-direction: column; gap: 10px;">
                    <label nz-radio *ngFor="let opt of currentQuestion?.options" [nzValue]="opt.text">
                        {{ opt.text }}
                    </label>
                </nz-radio-group>

                <div *ngIf="currentQuestion?.type === 'multi'" class="multi-option">
                    <label *ngFor="let opt of currentQuestion?.options">
                        <input type="checkbox"
                               [checked]="(answers[currentIndex] || []).includes(opt.text)"
                               (change)="toggleOption(opt.text)" />
                        {{ opt.text }}
                    </label>
                </div>

                <input *ngIf="currentQuestion?.type === 'short' || currentQuestion?.type === 'numeric'" nz-input placeholder="Введите ответ" [value]="answers[currentIndex]" (input)="onShortChange($event)" />

                <textarea *ngIf="currentQuestion?.type === 'essay'" nz-input rows="4" placeholder="Введите развернутый ответ" [value]="answers[currentIndex]" (input)="onShortChange($event)"></textarea>
            </nz-card>

            <div style="margin-top:16px; display:flex; justify-content:space-between;">
                <button nz-button (click)="prevQuestion()" [disabled]="currentIndex === 0">Назад</button>
                <button nz-button nzType="primary" *ngIf="currentIndex < questions.length - 1" (click)="nextQuestion()">Далее</button>
                <button nz-button nzType="primary" *ngIf="currentIndex === questions.length - 1" (click)="submitTest()" [nzLoading]="submitting">Завершить тест</button>
            </div>
            <nz-progress [nzPercent]="progressPercent" nzStatus="active" style="margin-top:16px;"></nz-progress>
        </div>

        <div *ngIf="!loading && questions.length === 0">
            <nz-alert nzType="info" nzMessage="В этом тесте нет вопросов"></nz-alert>
        </div>
    </nz-spin>
</div>

// frontend-react/src/pages/TestPassPage.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getTestById } from '../api/testApi';
import { getTestAttempts, createTestAttempt, updateTestAttempt } from '../api/testAttemptApi';
import { useAuth } from '../context/AuthContext';
import { parseGift } from '../utils/giftParser';
import { Button, Typography, Radio, Checkbox, Input, Space, message, Spin, Card, Divider, Alert, Progress } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';

const { Title, Paragraph } = Typography;

const TestPassPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const [test, setTest] = useState(null);
    const [questions, setQuestions] = useState([]);
    const [answers, setAnswers] = useState({});
    const [currentIndex, setCurrentIndex] = useState(0);
    const [loading, setLoading] = useState(true);
    const [submitting, setSubmitting] = useState(false);
    const [attemptId, setAttemptId] = useState(null);
    const initialized = useRef(false);
    const testIdNumber = parseInt(id);

    useEffect(() => {
        if (initialized.current) return;
        initialized.current = true;

        const initTest = async () => {
            try {
                const testRes = await getTestById(testIdNumber);
                setTest(testRes.data);
                const parsed = parseGift(testRes.data.content);
                setQuestions(parsed);
                const initialAnswers = {};
                parsed.forEach((q, idx) => {
                    if (q.type === 'short' || q.type === 'numeric' || q.type === 'essay') {
                        initialAnswers[idx] = '';
                    } else if (q.type === 'choice') {
                        initialAnswers[idx] = null;
                    } else if (q.type === 'multi') {
                        initialAnswers[idx] = [];
                    }
                });
                setAnswers(initialAnswers);

                const rolesString = user.roles ? user.roles.join(',') : '';
                const attemptsRes = await getTestAttempts({
                    testId: testIdNumber,
                    userId: user.id,
                    currentUserId: user.id,
                    roles: rolesString,
                    size: 10000
                });
                const attempts = attemptsRes.data.content || [];
                let inProgress = attempts.find(a => a.status === 'IN_PROGRESS');

                if (inProgress) {
                    setAttemptId(inProgress.id);
                    message.info('Продолжаем предыдущую попытку');
                } else {
                    const attemptNumber = attempts.length > 0 ? Math.max(...attempts.map(a => a.attemptNumber)) + 1 : 1;
                    const attemptData = {
                        testId: testIdNumber,
                        userId: user.id,
                        attemptNumber,
                        startTime: new Date().toISOString(),
                        endTime: null,
                        score: null,
                        status: 'IN_PROGRESS'
                    };
                    try {
                        const response = await createTestAttempt(attemptData);
                        const newAttempt = response.data || response;
                        setAttemptId(newAttempt.id);
                        message.success('Начат новый тест');
                    } catch (err) {
                        if (err.response?.status === 409 || err.message?.includes('duplicate')) {
                            const refreshAttempts = await getTestAttempts({
                                testId: testIdNumber,
                                userId: user.id,
                                currentUserId: user.id,
                                roles: rolesString,
                                size: 10000
                            });
                            const all = refreshAttempts.data.content || [];
                            const existing = all.find(a => a.status === 'IN_PROGRESS');
                            if (existing) {
                                setAttemptId(existing.id);
                                message.info('Продолжаем предыдущую попытку');
                            } else {
                                message.error('Не удалось создать попытку: конфликт');
                                setLoading(false);
                                return;
                            }
                        } else {
                            const errorMsg = err.response?.data?.message || err.message || 'Не удалось создать попытку';
                            message.error(errorMsg);
                            console.error(err);
                            setLoading(false);
                            return;
                        }
                    }
                }
            } catch (error) {
                message.error('Ошибка загрузки теста');
                console.error(error);
            } finally {
                setLoading(false);
            }
        };
        initTest();
    }, [testIdNumber, user]);

    const handleAnswerChange = (index, value) => {
        setAnswers(prev => ({ ...prev, [index]: value }));
    };

    const handleMultiChange = (index, checkedValues) => {
        setAnswers(prev => ({ ...prev, [index]: checkedValues }));
    };

    const handleShortChange = (index, e) => {
        setAnswers(prev => ({ ...prev, [index]: e.target.value }));
    };

    const renderQuestion = (q, idx) => {
        if (q.type === 'choice') {
            return (
                <Radio.Group
                    onChange={(e) => handleAnswerChange(idx, e.target.value)}
                    value={answers[idx]}
                    style={{ width: '100%' }}
                >
                    <Space direction="vertical" size="middle" style={{ width: '100%' }}>
                        {q.options.map((opt, i) => (
                            <Radio key={i} value={opt.text}>{opt.text}</Radio>
                        ))}
                    </Space>
                </Radio.Group>
            );
        }
        if (q.type === 'multi') {
            return (
                <Checkbox.Group
                    onChange={(checkedValues) => handleMultiChange(idx, checkedValues)}
                    value={answers[idx] || []}
                    style={{ width: '100%' }}
                >
                    <Space direction="vertical" size="middle" style={{ width: '100%' }}>
                        {q.options.map((opt, i) => (
                            <Checkbox key={i} value={opt.text}>{opt.text}</Checkbox>
                        ))}
                    </Space>
                </Checkbox.Group>
            );
        }
        if (q.type === 'short' || q.type === 'numeric') {
            return (
                <Input
                    placeholder="Введите ответ"
                    value={answers[idx] || ''}
                    onChange={(e) => handleShortChange(idx, e)}
                />
            );
        }
        if (q.type === 'essay') {
            return (
                <Input.TextArea
                    rows={4}
                    placeholder="Введите развернутый ответ"
                    value={answers[idx] || ''}
                    onChange={(e) => handleShortChange(idx, e)}
                />
            );
        }
        return <div>Неизвестный тип вопроса</div>;
    };

    const handleSubmit = async () => {
        let correctCount = 0;
        let totalQuestions = questions.length;
        questions.forEach((q, idx) => {
            const userAnswer = answers[idx];
            if (q.type === 'choice') {
                const correctOption = q.options.find(opt => opt.correct);
                if (correctOption && userAnswer === correctOption.text) {
                    correctCount++;
                }
            } else if (q.type === 'multi') {
                const correctOptions = q.options.filter(opt => opt.correct).map(opt => opt.text);
                const userOptions = userAnswer || [];
                const sortedCorrect = [...correctOptions].sort();
                const sortedUser = [...userOptions].sort();
                if (JSON.stringify(sortedCorrect) === JSON.stringify(sortedUser)) {
                    correctCount++;
                }
            } else if (q.type === 'short' || q.type === 'numeric') {
                if (q.correct && userAnswer && userAnswer.trim().toLowerCase() === q.correct.toLowerCase()) {
                    correctCount++;
                }
            } else if (q.type === 'essay') {
                if (userAnswer && userAnswer.trim() !== '') {
                    correctCount++;
                }
            }
        });

        const score = Math.round((correctCount / totalQuestions) * 100);

        setSubmitting(true);
        try {
            await updateTestAttempt(attemptId, {
                endTime: new Date().toISOString(),
                score: score,
                status: 'COMPLETED'
            });
            message.success(`Тест завершён! Вы набрали ${score}%`);
            navigate(`/tests/${testIdNumber}`);
        } catch (error) {
            message.error('Ошибка сохранения результатов');
            console.error(error);
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) return <Spin tip="Загрузка..." />;
    if (!test) return <div>Тест не найден</div>;
    if (!attemptId) return <div>Не удалось начать тест</div>;

    const currentQuestion = questions[currentIndex];

    return (
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
            <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)} style={{ marginBottom: 16 }}>
                Назад
            </Button>
            <Title level={2}>{test.title}</Title>
            <Paragraph>{test.description}</Paragraph>
            <Divider />
            {questions.length === 0 ? (
                <Alert message="В этом тесте нет вопросов" type="info" />
            ) : (
                <>
                    <div style={{ marginBottom: 16 }}>
                        <strong>Вопрос {currentIndex + 1} из {questions.length}</strong>
                    </div>
                    <Card>
                        <Paragraph strong>{currentQuestion.question}</Paragraph>
                        {renderQuestion(currentQuestion, currentIndex)}
                    </Card>
                    <div style={{ marginTop: 16, display: 'flex', justifyContent: 'space-between' }}>
                        <Button
                            onClick={() => setCurrentIndex(prev => Math.max(prev - 1, 0))}
                            disabled={currentIndex === 0}
                        >
                            Назад
                        </Button>
                        {currentIndex < questions.length - 1 ? (
                            <Button type="primary" onClick={() => setCurrentIndex(prev => prev + 1)}>
                                Далее
                            </Button>
                        ) : (
                            <Button type="primary" loading={submitting} onClick={handleSubmit}>
                                Завершить тест
                            </Button>
                        )}
                    </div>
                    <div style={{ marginTop: 16 }}>
                        <Progress percent={Math.round((currentIndex + 1) / questions.length * 100)} />
                    </div>
                </>
            )}
        </div>
    );
};

export default TestPassPage;
