// frontend-angular/src/app/pages/test-detail-page/test-detail-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { TestService } from '../../api/test.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Location } from "@angular/common";

@Component({
    selector: 'app-test-detail-page',
    templateUrl: './test-detail-page.component.html',
    styleUrls: ['./test-detail-page.component.scss']
})
export class TestDetailPageComponent implements OnInit {
    test: any = null;
    loading = true;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private testService: TestService,
        private message: NzMessageService,
        private location: Location
    ) {}

    ngOnInit(): void {
        const id = Number(this.route.snapshot.paramMap.get('id'));
        if (id) {
            this.loadTest(id);
        }
    }

    loadTest(id: number): void {
        this.loading = true;
        this.testService.getTestById(id).subscribe({
            next: (data) => {
                this.test = data;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить тест');
                this.loading = false;
            }
        });
    }

    goBack(): void {
        this.location.back();
    }

    startTest(): void {
        this.router.navigate(['/tests', this.test.id, 'pass']);
    }
}
<div class="container">
    <div class="back-row">
        <button nz-button nzType="default" (click)="goBack()">
            <i nz-icon nzType="arrow-left"></i> Назад
        </button>
        <hr class="flex-divider" />
    </div>
    <nz-spin [nzSpinning]="loading" [nzTip]="'Загрузка...'">
        <div *ngIf="test">
            <h2>{{ test.title }}</h2>
            <p>{{ test.description }}</p>
            <p><strong>Вопросов:</strong> {{ test.questionsCount }}</p>
            <button nz-button nzType="primary" (click)="startTest()">
                <i nz-icon nzType="play-circle"></i> Пройти тест
            </button>
        </div>
    </nz-spin>
</div>

// frontend-react/src/pages/TestDetailPage.jsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getTestById } from '../api/testApi';
import { Button, Typography, Spin } from 'antd';
import { ArrowLeftOutlined, PlayCircleOutlined } from '@ant-design/icons';

const { Title, Paragraph } = Typography;

const TestDetailPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [test, setTest] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        getTestById(id)
            .then(res => setTest(res.data))
            .catch(console.error)
            .finally(() => setLoading(false));
    }, [id]);

    if (loading) return <Spin tip="Загрузка..." />;
    if (!test) return <div>Тест не найден</div>;

    return (
        <div>
            <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)} style={{ marginBottom: 16 }}>
                Назад
            </Button>
            <Title level={2}>{test.title}</Title>
            <Paragraph>{test.description}</Paragraph>
            <Paragraph><strong>Вопросов:</strong> {test.questionsCount}</Paragraph>
            <Button type="primary" icon={<PlayCircleOutlined />} onClick={() => navigate(`/tests/${test.id}/pass`)}>
                Пройти тест
            </Button>
        </div>
    );
};

export default TestDetailPage;
