// frontend-react/src/components/CategoryList.js
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Modal, Form, Input, message, Spin } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { getCategories, createCategory, updateCategory, deleteCategory } from '../api/categoryApi';
import { useAuth } from '../context/AuthContext';

const { Column } = Table;

const CategoryList = () => {
    const { user } = useAuth();
    const isAdmin = user.roles?.includes('ADMIN') || false;
    const isTeacher = user.roles?.includes('TEACHER') || false;
    const canManage = isAdmin || isTeacher;

    const [categories, setCategories] = useState([]);
    const [loading, setLoading] = useState(false);
    const [modalVisible, setModalVisible] = useState(false);
    const [editingCategory, setEditingCategory] = useState(null);
    const [form] = Form.useForm();

    const [queryParams, setQueryParams] = useState({
        page: 0,
        size: 10,
        name: '',
    });
    const [paginationInfo, setPaginationInfo] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    const searchTimeout = useRef(null);

    useEffect(() => {
        fetchCategories();
    }, [queryParams]);

    const fetchCategories = async () => {
        setLoading(true);
        try {
            const params = { ...queryParams };
            if (!params.name) delete params.name;
            const res = await getCategories(params);
            const content = res.data.content || res.data;
            setCategories(content);
            if (res.data.content) {
                setPaginationInfo({
                    current: res.data.number + 1,
                    pageSize: res.data.size,
                    total: res.data.totalElements,
                });
            } else {
                setPaginationInfo({
                    current: 1,
                    pageSize: content.length,
                    total: content.length,
                });
            }
        } catch {
            message.error('Не удалось загрузить категории');
        } finally {
            setLoading(false);
        }
    };

    const handleTableChange = (pagination) => {
        setQueryParams(prev => ({
            ...prev,
            page: pagination.current - 1,
            size: pagination.pageSize,
        }));
    };

    const handleSearchChange = (e) => {
        const value = e.target.value;
        if (searchTimeout.current) clearTimeout(searchTimeout.current);
        searchTimeout.current = setTimeout(() => {
            setQueryParams(prev => ({
                ...prev,
                name: value,
                page: 0,
            }));
        }, 300);
    };

    const handleReset = () => {
        setQueryParams({
            page: 0,
            size: 10,
            name: '',
        });
    };

    const showModal = (category = null) => {
        setEditingCategory(category);
        form.resetFields();
        if (category) {
            form.setFieldsValue({
                name: category.name,
                description: category.description,
            });
        }
        setModalVisible(true);
    };

    const handleSubmit = async (values) => {
        try {
            if (editingCategory) {
                await updateCategory(editingCategory.id, values);
                message.success('Категория обновлена');
            } else {
                await createCategory(values);
                message.success('Категория создана');
            }
            setModalVisible(false);
            fetchCategories();
        } catch (error) {
            if (error.response?.status === 400) {
                const errors = Object.values(error.response.data).flat().join('\n');
                message.error(errors);
            } else if (error.response?.status === 409) {
                message.error('Категория с таким названием уже существует');
            } else {
                message.error('Ошибка сохранения');
            }
        }
    };

    const handleDelete = (id) => {
        Modal.confirm({
            title: 'Удалить категорию?',
            content: 'Это действие необратимо.',
            okText: 'Да, удалить',
            okType: 'danger',
            cancelText: 'Отмена',
            onOk: async () => {
                try {
                    await deleteCategory(id);
                    message.success('Категория удалена');
                    fetchCategories();
                } catch {
                    message.error('Ошибка удаления');
                }
            }
        });
    };

    return (
        <Spin spinning={loading}>
            <div style={{ padding: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                    <Space>
                        <Input
                            placeholder="Поиск по названию"
                            allowClear
                            value={queryParams.name}
                            onChange={handleSearchChange}
                            style={{ width: 250 }}
                        />
                        <Button onClick={handleReset}>Сбросить</Button>
                    </Space>
                    {canManage && (
                        <Button type="primary" icon={<PlusOutlined />} onClick={() => showModal()}>
                            Добавить категорию
                        </Button>
                    )}
                </div>

                <Table
                    dataSource={categories}
                    rowKey="id"
                    pagination={{
                        current: paginationInfo.current,
                        pageSize: paginationInfo.pageSize,
                        total: paginationInfo.total,
                        showSizeChanger: true,
                        pageSizeOptions: ['5', '10', '20', '50'],
                    }}
                    onChange={handleTableChange}
                    loading={loading}
                >
                    {isAdmin && <Column title="ID" dataIndex="id" />}
                    <Column
                        title="Название"
                        render={(_, category) => (
                            <Link to={`/categories/${category.id}`}>{category.name}</Link>
                        )}
                    />
                    <Column title="Описание" dataIndex="description" />
                    {canManage && (
                        <Column
                            title="Действия"
                            render={(_, category) => (
                                <Space>
                                    <Button icon={<EditOutlined />} onClick={() => showModal(category)} />
                                    <Button icon={<DeleteOutlined />} danger onClick={() => handleDelete(category.id)} />
                                </Space>
                            )}
                        />
                    )}
                </Table>

                <Modal
                    title={editingCategory ? 'Редактировать категорию' : 'Новая категория'}
                    open={modalVisible}
                    onOk={() => form.submit()}
                    onCancel={() => setModalVisible(false)}
                >
                    <Form form={form} onFinish={handleSubmit} layout="vertical">
                        <Form.Item name="name" label="Название" rules={[{ required: true }]}>
                            <Input />
                        </Form.Item>
                        <Form.Item name="description" label="Описание">
                            <Input.TextArea />
                        </Form.Item>
                    </Form>
                </Modal>
            </div>
        </Spin>
    );
};

export default CategoryList;

// frontend-angular/src/app/components/category-list/category-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CategoryService } from '../../api/category.service';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
    selector: 'app-category-list',
    templateUrl: './category-list.component.html',
    styleUrls: ['./category-list.component.scss']
})
export class CategoryListComponent implements OnInit {
    categories: any[] = [];
    loading = false;
    pageIndex = 1;
    pageSize = 10;
    total = 0;
    searchName = '';
    isVisible = false;
    isEdit = false;
    editId: number | null = null;
    form: FormGroup;

    constructor(
        private categoryService: CategoryService,
        public auth: AuthService,
        private fb: FormBuilder,
        private message: NzMessageService,
        private modal: NzModalService
    ) {
        this.form = this.fb.group({
            name: ['', Validators.required],
            description: ['']
        });
    }

    ngOnInit(): void {
        this.loadCategories();
    }

    canManage(): boolean {
        return this.auth.isAdmin() || this.auth.isTeacher();
    }

    loadCategories(): void {
        this.loading = true;
        const params = {
            page: this.pageIndex - 1,
            size: this.pageSize,
            name: this.searchName || undefined
        };
        this.categoryService.getCategories(params).subscribe({
            next: (res) => {
                this.categories = res.content;
                this.total = res.totalElements;
                this.loading = false;
            },
            error: () => {
                this.message.error('Не удалось загрузить категории');
                this.loading = false;
            }
        });
    }

    onPageChange(page: number): void {
        this.pageIndex = page;
        this.loadCategories();
    }

    resetSearch(): void {
        this.searchName = '';
        this.pageIndex = 1;
        this.loadCategories();
    }

    showModal(data?: any): void {
        this.isEdit = !!data;
        this.editId = data?.id || null;
        this.form.reset();
        if (data) {
            this.form.patchValue({
                name: data.name,
                description: data.description
            });
        }
        this.isVisible = true;
    }

    handleOk(): void {
        if (this.form.invalid) {
            Object.values(this.form.controls).forEach(c => c.markAsDirty());
            return;
        }
        const values = this.form.value;
        const obs = this.isEdit
            ? this.categoryService.updateCategory(this.editId!, values)
            : this.categoryService.createCategory(values);
        obs.subscribe({
            next: () => {
                this.message.success(this.isEdit ? 'Категория обновлена' : 'Категория создана');
                this.isVisible = false;
                this.loadCategories();
            },
            error: (err) => {
                if (err.status === 409) {
                    this.message.error('Категория с таким названием уже существует');
                } else {
                    this.message.error(err.error?.message || 'Ошибка сохранения');
                }
            }
        });
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    deleteCategory(id: number): void {
        this.modal.confirm({
            nzTitle: 'Удалить категорию?',
            nzContent: 'Это действие необратимо.',
            nzOkText: 'Удалить',
            nzCancelText: 'Отмена',
            nzOkDanger: true,
            nzOkType: 'primary',
            nzOnOk: () => {
                this.categoryService.deleteCategory(id).subscribe({
                    next: () => {
                        this.message.success('Категория удалена');
                        this.loadCategories();
                    },
                    error: () => this.message.error('Ошибка удаления')
                });
            }
        });
    }

    isAdmin(): boolean {
        return this.auth.isAdmin();
    }

    searchTimeout: any;

    onSearchChange(value: string): void {
        if (this.searchTimeout) clearTimeout(this.searchTimeout);
        this.searchTimeout = setTimeout(() => {
            this.searchName = value;
            this.pageIndex = 1;
            this.loadCategories();
        }, 300);
    }
}
<div class="container">
    <div class="actions">
        <input nz-input placeholder="Поиск по названию" [(ngModel)]="searchName" (ngModelChange)="onSearchChange($event)" style="width:250px;" />
        <button nz-button (click)="resetSearch()">Сбросить</button>
        <button nz-button nzType="primary" *ngIf="canManage()" (click)="showModal()" class="add-btn">Добавить категорию</button>
    </div>

    <nz-table
            [nzData]="categories"
            [nzLoading]="loading"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzPageIndex]="pageIndex"
            (nzPageIndexChange)="onPageChange($event)"
            nzNoResult="Нет данных"
            [nzFrontPagination]="false"
    >
        <thead>
        <tr>
            <th *ngIf="isAdmin()">ID</th>
            <th>Название</th>
            <th>Описание</th>
            <th *ngIf="canManage()">Действия</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let cat of categories">
            <td *ngIf="isAdmin()">{{ cat.id }}</td>
            <td><a [routerLink]="['/categories', cat.id]">{{ cat.name }}</a></td>
            <td>{{ cat.description }}</td>
            <td *ngIf="canManage()">
                <button nz-button nzType="link" (click)="showModal(cat)"><i nz-icon nzType="edit"></i></button>
                <button nz-button nzType="link" nzDanger (click)="deleteCategory(cat.id)"><i nz-icon nzType="delete"></i></button>
            </td>
        </tr>
        </tbody>
    </nz-table>

    <nz-modal
            [(nzVisible)]="isVisible"
            [nzTitle]="isEdit ? 'Редактировать категорию' : 'Новая категория'"
            nzOkText="Сохранить"
            nzCancelText="Отмена"
            (nzOnCancel)="handleCancel()"
            (nzOnOk)="handleOk()"
    >
        <ng-template nzModalContent>
            <form nz-form [formGroup]="form">
                <nz-form-item>
                    <nz-form-label>Название</nz-form-label>
                    <nz-form-control [nzErrorTip]="'Обязательное поле'">
                        <input nz-input formControlName="name" />
                    </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                    <nz-form-label>Описание</nz-form-label>
                    <nz-form-control>
                        <textarea nz-input formControlName="description"></textarea>
                    </nz-form-control>
                </nz-form-item>
            </form>
        </ng-template>
    </nz-modal>
</div>
