// frontend-react/src/pages/LoginPage.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Form, Input, Button, message, Card } from 'antd';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

const LoginPage = () => {
    const [loading, setLoading] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const onFinish = async (values) => {
        setLoading(true);
        try {
            const response = await axios.post(`${process.env.REACT_APP_API_URL}/auth/login`, {
                username: values.username,
                password: values.password,
            });
            const userData = response.data;
            login(userData);
            message.success('Вы вошли как ' + userData.roleDescription);
            navigate('/');
        } catch (error) {
            if (error.response) {
                const errorMessage = typeof error.response.data === 'string'
                    ? error.response.data
                    : error.response.data?.message || 'Ошибка входа';
                message.error(errorMessage);
            } else {
                message.error('Сервер не отвечает. Проверьте подключение.');
            }
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
            <Card title="Вход в LMS" style={{ width: 400 }}>
                <Form onFinish={onFinish} layout="vertical">
                    <Form.Item name="username" label="Логин или Email" rules={[{ required: true }]}>
                        <Input placeholder="Введите логин или email" />
                    </Form.Item>
                    <Form.Item name="password" label="Пароль" rules={[{ required: true }]}>
                        <Input.Password placeholder="Введите пароль" />
                    </Form.Item>
                    <Form.Item>
                        <Button type="primary" htmlType="submit" loading={loading} block>
                            Войти
                        </Button>
                    </Form.Item>
                </Form>
            </Card>
        </div>
    );
};

export default LoginPage;

// frontend-angular/src/app/pages/login-page/login-page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../api/auth.service';
import { NzMessageService } from 'ng-zorro-antd/message';

@Component({
    selector: 'app-login-page',
    templateUrl: './login-page.component.html',
    styleUrls: ['./login-page.component.scss']
})
export class LoginPageComponent implements OnInit {
    loginForm: FormGroup;
    loading = false;

    constructor(
        private fb: FormBuilder,
        public  auth: AuthService,
        private router: Router,
        private message: NzMessageService
    ) {
        this.loginForm = this.fb.group({
            username: ['', Validators.required],
            password: ['', Validators.required]
        });
    }

    ngOnInit(): void {
        if (this.auth.getUser()) {
            this.router.navigate(['/']);
        }
    }

    submitForm(): void {
        if (this.loginForm.invalid) {
            Object.values(this.loginForm.controls).forEach(c => c.markAsDirty());
            return;
        }
        this.loading = true;
        const { username, password } = this.loginForm.value;
        this.auth.login({ username, password }).subscribe({
            next: () => {
                this.message.success('Вы вошли как ' + this.auth.getUser()?.roleDescription);
                this.router.navigate(['/']);
                this.loading = false;
            },
            error: (err) => {
                const msg = err.error?.message || 'Ошибка входа';
                this.message.error(msg);
                this.loading = false;
            }
        });
    }
}
<div class="login-container">
    <nz-card nzTitle="Вход в LMS" style="width:400px;">
        <form nz-form [formGroup]="loginForm" (ngSubmit)="submitForm()">
            <nz-form-item>
                <nz-form-label [nzSpan]="24">Логин</nz-form-label>
                <nz-form-control [nzSpan]="24" [nzErrorTip]="'Обязательное поле'">
                    <input nz-input formControlName="username" placeholder="Введите логин" />
                </nz-form-control>
            </nz-form-item>
            <nz-form-item>
                <nz-form-label [nzSpan]="24">Пароль</nz-form-label>
                <nz-form-control [nzSpan]="24" [nzErrorTip]="'Обязательное поле'">
                    <input nz-input type="password" formControlName="password" placeholder="Введите пароль" />
                </nz-form-control>
            </nz-form-item>
            <nz-form-item>
                <nz-form-control [nzSpan]="24">
                    <button nz-button nzType="primary" htmlType="submit" [nzLoading]="loading" block>
                        Войти
                    </button>
                </nz-form-control>
            </nz-form-item>
        </form>
    </nz-card>
</div>
